### ISSUE TITLE
Read the Beatsync if it's on when Wipe&Slice

### ISSUE THREAD

**Issue by vsctmby** [esaruoho/org.lackluster.Paketti.xrnx#100]
As per the topic. Just read the Beatsync value instead of making it 128 currently, and split the remaining slices according to that value.

**Comment by esaruoho** [comment]
@vsctmby quick question, if beatsync is set to 17 and i create 2 slices, what should the beatsync values be?

**Comment by esaruoho** [comment]
@vsctmby if beatsync is 16 and i have 128 slices.. then what?

**Comment by vsctmby** [comment]
If beatsync is 16, and you can't make smaller than 1 line slices with a
beatsync on, then it shouldn't be possible to make more slices than the
specific beatsync value.

Alternatively, you could make it so that if the user wants to create 128
slices of 16 beatsync sample, then the beatsync is just off on the slices
themselves.

But my main use case would be anyway on taking a 32 line beatsynced sample,
slice it to 8 slices and just not screw up the beatsync I already assigned
for the sample.

**Comment by esaruoho** [comment]
ok.

wipe&slice improvements:
- if you have beatsyncmode + lines set, it will set the beatsync lines for slices accordingly. - meaning, if your original loop is at beatsync 128.. and you create 64 slices - then each slice will be at beatsync 2. if you have beatsync 128 and you create 2 slices, each slice will be at beatsync 64 and so on.
- if you don't have beatsyncmode, then don't assign beatsyncmode by default, i.e. keep all slices playing as expected.

thanks!
