### ISSUE TITLE
Phrase Repository

### ISSUE THREAD

**Issue by ghost** [esaruoho/org.lackluster.Paketti.xrnx#102]
I would like something along the lines of a Phrase repository.

I would like a keybind that copies the current pattern in the editor and paste it along with the line settings into the next blank phrase slot and create one if it doesn't exist. Also I would like this tool to have a keybind that copies the **currently selected phrase** data into the current pattern after clearing the data in the pattern editor track. The goal is to be able use the phrases as a live sketchpad.

I would need the pattern editor data copied instead of triggering the phrases with single notes. I would like to SEE the phrase data and audition different takes. The only issue I see is copying over phrases with different LPB settings than the global LPB. 

If a phrase is shorter than the lines per pattern than just paste continually. I sponsored a tool called TTP but it includes many more features in addition to a GUI which is not needed. I would just like the core function of that tool available to everyone in Paketti.

**Comment by esaruoho** [comment]
@icasiino please add a link to "tool called TTP" to this thread

i edited some of this post a little bit. it's gonna be interesting looking at how to do this. by "current pattern" i think "current selected track note/effect content", right?

**Comment by icasiino** [comment]
By "current pattern" I mean currently selected track, yes. And here is TTP 

https://forum.renoise.com/t/new-tool-3-4-3-travel-through-phrases-v1-2-build-052-november-2023/70729

**Comment by esaruoho** [comment]
this requires bunches of stuff to be implemented in the api and i'm tagging it as maybe + and not planned right now.
