### ISSUE TITLE
Wrap/Rotate sample in sample editor

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#110]
"In sample editor it would be super awesome to be able to wrap sample around the edges so to speak, just like using rotate tool for editor. (in Reaper you can do it when press alt while dragging the waveform, very useful)" from Reddit

from https://forum.renoise.com/t/anther-suggestions/12341

- [x] shift selection left/right
- [ ] rotate audio

but what does rotate audio mean?

rotate audio rotates for 1/4 the selection. for example if you take a standart beat loop and make “rotate audio” once then you’ll get snare drum goes first (instead bassdrum), and that bassdrum will be on last 1/4 part of loop.

**Comment by esaruoho** [comment]
ok, one of these is almost done. - two midiknobs for moving backwards + forwards.
![hows this for offset](https://github.com/user-attachments/assets/d4c0b684-83ba-4f03-a03a-b252d4744fc5)

the 1/4 i think should be a different ticket.


but what does rotate audio mean?

rotate audio rotates for 1/4 the selection. for example if you take a standart beat loop and make “rotate audio” once then you’ll get snare drum goes first (instead bassdrum), and that bassdrum will be on last 1/4 part of loop.

**Comment by dmt-hub** [comment]
please add coarse sample offset nudge (L-R) shortcut option - and maybe a wide slider dialog - when moving the slider it moves the sample L->R
