### ISSUE TITLE
List Available Plugins/Effects - Renoise 3.4.3 / Win10

### ISSUE THREAD

**Issue by untilde** [esaruoho/org.lackluster.Paketti.xrnx#120]
Stumbled upon this error today:

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/20494933/242c44d9-3655-480e-aa21-ffa5f52b3510)

Happens with all the options in this section of the submenu.

Tried to interpret the error but still have no clue. Problem may be on my side, but reporting it just in case.

PS: Using the latest version of Paketti (3.54).

**Comment by esaruoho** [comment]
Tahnaksi @untilde , will fix soon

**Comment by esaruoho** [comment]
meant to write thanks, @untilde -- autocorrect got in the way

**Comment by esaruoho** [comment]
ok, that was easy to fix. pesky `local function` stuff. here's a fix.
btw, this menu entry has been moved to Main Menu -> Tools -> Paketti.. -> Plugins/Devices -> List Available VST3 Effects.
<img width="1050" alt="Screenshot 2024-05-25 at 16 48 59" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/8955f621-e545-4e60-a04e-911f5c10dec5">

check this build out (it seems you're using a rather old one..

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/releases/tag/20240525135312

**Comment by esaruoho** [comment]
@untilde if it no longer errors for you, please close ticket 👍

**Comment by esaruoho** [comment]
i also fixed this to work again:
<img width="1286" alt="Screenshot 2024-05-25 at 17 06 20" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/3ce378d4-35c0-4361-a6f4-de267cef0300">

thanks for pointing this my way.
here's a VIP WIP
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15443806/org.lackluster.Paketti_V3.54.xrnx.zip)

i should really get to modifying that to loading VST Efx, AU Efx, VST3 Efx. It's been so long on my list.

**Comment by esaruoho** [comment]
adding more focus to #25  now.

**Comment by untilde** [comment]
Sorry for the delay, didn't check GitHub for a couple days. Issue looks solved.

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/20494933/590675f6-ef06-4954-ba19-db184d2be427)

Thanks again for the hard work!

**Comment by untilde** [comment]
Sorry for the delay, didn't check GitHub for a couple days. Issue looks solved.

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/20494933/d09b44e5-8f2f-4256-b403-7977ab8c7981)

Thanks again for the hard work!
