### ISSUE TITLE
What to do about Midi Commands (10xx to Yxxx?)

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#136]
<img width="1182" alt="Screenshot 2024-07-30 at 8 25 15" src="https://github.com/user-attachments/assets/5b342a48-4dd5-477d-8808-e6a3c1a3dc36">

**Comment by esaruoho** [comment]
uhh i don't think this screenshot is the one i wanted to add.

**Comment by esaruoho** [comment]
so, what Renoise does, is take the 1st dsp device, and do 10xx to 1Zxx - but that's of course limited. 
.. you can even get to "Y2" which seems to be the maximum
```
>>> oprint (renoise.song().selected_device_index)
35
```
so there's this massive amount of space, that can be modified. but i don't know what to do about it.

**Comment by tkna91** [comment]
What is it about? Is it about how to control MIDI commands with cheat sheets?

**Comment by esaruoho** [comment]
i don't think i can do anything about them, and it doesn't make sense to start going the dynamic route. closing.
