### ISSUE TITLE
sample selector 

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#157]
https://forum.renoise.com/t/sample-selector/72520

Is there a way I can load a lot of samples in an instrumet and have a slider to choose which sample is played?

Basically I would like to make some kick or other drum selectors.

i think one might be able to script this. i.e. have a selector of which to play, and the rest would have 0 volume. so like a midiknob 0…127 and depending on where you’re at, all the others are silent.

**Comment by dmt-hub** [comment]
yes great idea - like a sample selector
a gui slider / linkable to midi
then being able to modulate this slider
would that even be possible?
load in 100+ snares, then choose one with the slider while the track is playing

**Comment by esaruoho** [comment]
midislider + keybindings done. a gui slider would need to be set a bit later. maybe some sort of multi-instrument drumkit selector type dialog, i.e. load 120 kicks 120 snares 120 hihats 120 openhihats 120 claps and then ..
this sounds like a drummachine gui.
