### ISSUE TITLE
Add sample properties key bind settings

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#16]
Please consider adding a feature to allow control over sample properties.
It looks like the following:
Increase/Decrease units seem to be as per the basic GUI button, but it may be useful to add a type of adjustment unit depending on how it is used.

- Sample Editor
    - Paketti
        - Volume Increase
        - Volume Decrease
        - Panning Increase
        - Panning Decrease
        - Transpose Increase
        - Transpose Decrease
        - Finetune Increase
        - Finetune Decrease
        - Beatsync toggle
        - Beatsync Mode to 1 Repitch
        - Beatsync Mode to 2 Time-Stretch (Percussion)
        - Beatsync Mode to 3 Time-Stretch (Texture)
        - Beatsync [T] button
        - Loop Finish
        - Mute Group None
        - Mute Group 1
        - Mute Group 2
        - Mute Group 3
        - Mute Group 4
        - Mute Group 5
        - Mute Group 6
        - Mute Group 7
        - Mute Group 8
        - Mute Group 9
        - Mute Group A
        - Mute Group B
        - Mute Group C
        - Mute Group D
        - Mute Group E
        - Mute Group F
        - Mute Group G
        - NNA Cut
        - NNA Note-Off
        - NNA Continue
        - Playback Autofade toggle
        - Playback Autoseek toggle
        - Anti-aliasing toggle
        - Quality None
        - Quality Linear
        - Quality Cubic
        - Quality Sinc

https://tutorials.renoise.com/wiki/Sampler#Sample_Properties

**Comment by esaruoho** [comment]
@tkna91 thanks for hitting up my repo! it's a better way of reaching me than the renoiseforum.
Now, could we talk about what specific ways of controlling you want for these.
I could easily write shortcuts for Mute Group None to Mute Group G i think, and NNA switchings, but the Transpose, Volume, Panning, Finetune increase+decrease stuff, are you looking for sliders i.e. a GUI, or?

It'd be really beneficial if you could break this down to what you want. i can do cycles (like the Quality change could be +1 -1 and when it hits Sinc and you do a +1, it gets back to None), or specific shortcuts for setting to a specific one (one shortcut for Cubic, one for Sinc).

but before venturing out, since this is a request by you and not my own thinking, i'd prefer to be doing what you want rather than what i think makes sense. I have never used any of these.

let's keep this conversation going? please tell me in great detail what you want, and i'll have a look.

**Comment by tkna91** [comment]
As for my own needs, my initial idea was that better access to tone parameter changes for drum kit parts like the TR-909, as shown below, would make it easier to compose.

https://extralifeinstruments.com/er-99/

Screencast with sound:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/93f4663b-f2a6-47c4-a0de-975658758d08

Screencast with sound:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/c198908d-8eb1-4944-bde7-1f760ad9b53e

I want to control these with the keyboard (key bindings).

Mapping to MIDI controllers and macros in these parameters and control with GUI knobs is not possible by default, and probably can be done with the following tools, but setting to key bindings does not seem to be possible.

https://forum.renoise.com/t/new-tool-3-4-3-sample-multi-controller-v2-1-build-060-get-more-out-of-renoise-s-sampler/

Can you first add key bindings to manipulate the following parameters in the current sample?
For now, I am thinking that the unit of value is the same as the up/down button (<>) and that there is no problem.

- Volume Increase(+0.1)
- Volume Decrease(-0.1)
- Panning Increase(+1)
- Panning Decrease(-1)
- Transpose Increase(+1)
- Transpose Decrease(-1)
- Finetune Increase(+1)
- Finetune Decrease(-1)

screeenshot:
![20231127-020936_screenshot](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/7218f833-c340-407d-aa71-3d4c31cb2b51)

**Comment by esaruoho** [comment]
@tkna91 

hi, the screencasts look like this on my browser:
<img width="469" alt="Screenshot 2023-12-04 at 21 13 14" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/2b201005-062c-494b-825e-89235d69cc67">

so it appears they don't work. can you upload them to a YouTube account and make them unlisted and send a link to me? :)

**Comment by tkna91** [comment]
> hi, the screencasts look like this on my browser:

I found out how to encode it for playback in firefox.

https://support.mozilla.org/en-US/questions/1379414
```bash
ffmpeg -i $in -pix_fmt yuv420p -c:a copy -movflags +faststart $out
```
Perhaps this will help you play it back.

Screencast with sound:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/7c4c20a8-567f-4e76-b6c3-b110ab5a2bbc

Screencast with sound:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/f6ec5006-5e37-4808-86c6-7951d11e2ecd

**Comment by tkna91** [comment]
> what would, in your mind, be the simplest solution that gives you something workable that you can test and come back with additional feature requests?

It is  that "select a sample within an instrument manually, then change it's pitch".
I think it is ideal that by playing the sample on the keyboard, the object is selected and subject to parameter change. This would allow for intuitive and quick parameter changes without the use of numerous shortcut keys.

**Comment by tkna91** [comment]
In other words, in the above video, the operation is as follows

1. enter key `x`; The note `D-2` is played and selected.
2. Enter `any key binding` set by Paketti; Transpose is changed by `+1`.
3. Enter `any key binding` set by Paketti; Transpose is changed by `-1`.

**Comment by tkna91** [comment]
Then the user can detach and display the sample editor to visually check the transpose values while editing the pattern, etc.

Screencast with sound:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/82ace35c-9877-4bfa-b9f9-0c6269b10615

**Comment by esaruoho** [comment]
> If possible, I would like to be able to change the transpose without displaying the sample editor view. This would be great because it would allow me to change the scale of each drum kit even while creating patterns. 

i've found a way to do this. i don't need to have Sample Editor displaying to see which one is selected. as long as 
this is set:
<img width="417" alt="Screenshot 2023-12-10 at 13 52 35" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/c175a108-f97a-4290-a8fa-df0bdb921471">

in that way, i have done an experiment where if i press C-1 and sample X is selected - the transpose is set to "some number" (that i've selected at random). then i press C#1 and sample Y is selected - the transpose is set to "some number y" (that i've selected at random).

i can do +1 -1 for you and +12 -12 for selected instrument selected sample, and cap it at -120 and +120, but i'm not sure if i know which shortcut would be good for you. i don't really know how i'd use these myself, unless if i set up my Behringer BCF2000 fader controller up (which provides 8 faders that i could use). but i'll continue tinkering with this a bit since this brings me back to updating Paketti.

Is there something specific you'd like to call this?

**Comment by esaruoho** [comment]
ok i have a shortcut that sets the currently selected sample's transposition to 0 (so init zero). i'll see what else i can do with the limited time i have.

**Comment by esaruoho** [comment]
ok i have a shortcut that does +1 and -1 to current transposition of current sample. it doesn't yet have protection against -120 and 120 but should be trivial to do.

**Comment by esaruoho** [comment]
ok i have -120 120 protection and +12 -12 +1 -1 for transpose. i'll see what else i can do but sounds like i ran out of time right now. i feel like for something like this, sliders in the UI would be better, but maybe i'm wrong.
and i can do midicontrols for this too.
can you provide more details of what you'd like next?

**Comment by esaruoho** [comment]
was looking through other paketti legacy shortcuts and realized a better way of getting the transpositions to work. the only catch now is that if you're in record mode and you press say C#4 - since the sample is not played, the sample is not selected, so you can't just press C#4 and then start transposing C#4 up. it needs to be played. (or selected by hand from F3 Sample Editor)

**Comment by esaruoho** [comment]
selected_sample interpolation settings for none, linear, cubic, sinc. that was easy.
<img width="341" alt="Screenshot 2023-12-10 at 22 10 24" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/01de9056-904a-4d24-9dcb-8b0caf0bb2ea">

**Comment by esaruoho** [comment]
<img width="335" alt="Screenshot 2023-12-10 at 22 17 22" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/301f0779-e3b0-44f3-a1c3-e6afe15aa2ef">

took me a while to figure out what it was called, but there it is. on, off, or toggle.

**Comment by esaruoho** [comment]
<img width="325" alt="Screenshot 2023-12-10 at 22 20 31" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/159158d6-3025-4a17-ac70-3d11e9d76958">

**Comment by esaruoho** [comment]
<img width="322" alt="Screenshot 2023-12-10 at 22 24 55" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/731d7567-dd93-405e-bb85-4888eec8e19c">

**Comment by esaruoho** [comment]
<img width="318" alt="Screenshot 2023-12-10 at 22 28 55" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/b701ac8f-9127-49a5-9009-ce3fd7ed0b2d">
<img width="241" alt="Screenshot 2023-12-10 at 22 28 59" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/877b99b0-d569-435b-a872-a2ef77bc8ecc">

**Comment by esaruoho** [comment]
> * Sample Editor
>   * Paketti
>     * Loop Finish

please can you @tkna91 tell me a bit more about what you mean by Loop Finish. Which part of the UI is it?

**Comment by esaruoho** [comment]
<img width="333" alt="Screenshot 2023-12-10 at 22 36 39" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/761c39ce-3f84-4e25-8d73-0df1d0feb209">

**Comment by esaruoho** [comment]
panning was a different beast, i needed to make it +0.01 and -0.01 for it to cover all the bases. i also added hard left and hard right and center shortcuts.
<img width="327" alt="Screenshot 2023-12-10 at 23 02 50" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/241178fd-bf9a-4e4c-a3e8-f29fd46d1dc2">

**Comment by esaruoho** [comment]
<img width="319" alt="Screenshot 2023-12-10 at 23 38 36" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/814085a7-e03b-4120-a1de-b401b9ce4b9e">

**Comment by esaruoho** [comment]
> It is that "select a sample within an instrument manually, then change it's pitch". I think it is ideal that by playing the sample on the keyboard, the object is selected and subject to parameter change. This would allow for intuitive and quick parameter changes without the use of numerous shortcut keys.

yes. i see what you're getting at. i've been writing these. i'm still vague on that one loop thing you mentioned, "Finish Loop". do you mean switching from Forwards, Backwards/Reverse, PingPong? and the beatsync. i'm trying to cover the listings you gave. so far i'm making some good headway.

**Comment by esaruoho** [comment]
> * Sample Editor
>   * Paketti
>     * Beatsync toggle

good news, i can do this. it's there as a toggle now and it works.
<img width="337" alt="Screenshot 2023-12-10 at 23 59 09" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/3b2d4288-5915-46e8-9d1d-6b0d39196d65">

>     * Beatsync Mode to 1 Repitch
>     * Beatsync Mode to 2 Time-Stretch (Percussion)
>     * Beatsync Mode to 3 Time-Stretch (Texture)
>     * Beatsync [T] button

bad news, i cannot find these anywhere in the API. maybe they're not possible to be set. i've tried looking for repitch, beatsync, beat_sync, stretch.. etc. no luck.

>     * Loop Finish

still not sure what this means, please help.

**Comment by esaruoho** [comment]
@tkna91 
<img width="258" alt="Screenshot 2023-12-11 at 10 19 19" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/862eb12c-55cf-440f-80ac-b521f79f81e6">
<img width="341" alt="Screenshot 2023-12-11 at 10 20 11" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/b09ba184-10f0-4bf7-80a8-141c9b435372">

ok here's some questions:
1. should beatsync type shortcut (percussion, texture, repitch) turn beatsync ON?
2. should beatsyncline = 0 equal beatsync toggled OFF?
3. should beatsyncline over 0 equal beatsync toggled ON? (so if i'm using +1 -1)

**Comment by tkna91** [comment]
Amazing. You've implemented a lot.

> > * Loop Finish

> still not sure what this means, please help.

This is about this. Can't this be manipulated by the API?

https://tutorials.renoise.com/wiki/Sampler#Sample_Properties

- Loop Finish: Toggles whether a sample will instantly stop or finish its current loop after a Note-Off input.

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/c03fc1f8-5706-46d1-bbc6-db39b462409d)

> 1. should beatsync type shortcut (percussion, texture, repitch) turn beatsync ON?

I don't think it is necessary. It certainly looks like it would be useful if it worked as a toggle, but I feel that it would be better to have it function individually as per the GUI anyway, so that we can associate the look with the key action.

> 2. should beatsyncline = 0 equal beatsync toggled OFF?
> 3. should beatsyncline over 0 equal beatsync toggled ON? (so if i'm using +1 -1)

I don't think it is necessary.
The GUI does not appear to allow Beatsync to be set to 0.

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/4632b7a8-c0b1-4691-a8a7-7615806d12fe

That would mean that the entire sample would be played back in 0 line minutes, which is logically not possible, but I don't think that would mean that Beatsync would be Off.

**Comment by esaruoho** [comment]
> Amazing. You've implemented a lot.

I think I implemented all of it. if i missed stuff, please let me know?
 
> > > * Loop Finish
> > still not sure what this means, please help.
> This is about this. Can't this be manipulated by the API?
> https://tutorials.renoise.com/wiki/Sampler#Sample_Properties
> * Loop Finish: Toggles whether a sample will instantly stop or finish its current loop after a Note-Off input.

i found it now. will implement. it was called loop_release.
<img width="341" alt="Screenshot 2023-12-11 at 12 28 38" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/d9f2199c-7b00-444f-a709-ab56e1a0dc31">

**Comment by esaruoho** [comment]
> > 3. should beatsyncline over 0 equal beatsync toggled ON? (so if i'm using +1 -1)
> I don't think it is necessary. The GUI does not appear to allow Beatsync to be set to 0.
> That would mean that the entire sample would be played back in 0 line minutes, which is logically not possible, but I don't think that would mean that Beatsync would be Off.

i mean if i have +1 and -1 for beatsync changing. beatsync is off. i press  +1 for beatsync. it is turned ON.
then i press -1 for beatsync, which is now at 1, then it detects, oh, beatsync is 1, and user wants -1, that means, turn beatsync OFF.
so this is going "outside" of Renoise limitations, to go "well if user wants less than the first beatsync line (1 is minimum renoise can have), then the 1 -1 = 0 which means = turn beatsync off.
it's not about "beatsync lines = 0" - that is not possible.
but it's about "oh, beatsynclines = 1, user wants -1  == turn beatsync off"

**Comment by esaruoho** [comment]
> Sorry if my interpretation is wrong. It means that if the user keeps lowering the value of Beatsync-line, Beatsync will be Disable at the end, right? 

This is what I am saying.
By creating a shortcut in Renoise that increases or decreases the BeatsyncLine number, we can go from 1 to 512.
512 will be maximum. 1 will be minimum. if BeatsyncLine number is 1, and user presses shortcut "Set Selected Sample BeatsyncLine -1" which removes 1 from 1, the script will then go "aha, you're trying to set BeatsyncLine to 0. This is not possible. But I will do a better thing. I will make BeatsyncLine be 0, by disabling BeatsyncLine.
and if the user then presses shortcut "Set Selected Sample BeatsyncLine +1" which adds +1 to the BeatsyncLine, then we will go from "Beatsync disabled" to "Beatsync enabled, with BeatsyncLine 1".
That is all that i am saying.
in this case, one shortcut will remove BeatsyncLines 1 at a time, and instead of requiring you to press another shortcut to disable Beatsync, it will automatically toggle Beatsync off, when user tries to set BeatsyncLine to 0. The script will catch the 1-1 and go "aha, user wants Beatsync = Off".

> Wouldn't the operation look like this? 

yes but without clicking "Beatsync Toggle Off".

>I think it would be simpler and easier to understand if the enabling/disabling of Beatsync itself is not associated with the manipulation of the Beatsync-line value, what do you think?

That's why I'm both giving you "Beatsync Toggle On/Off" shortcut, and "BeatsyncLine +1" and "BeatsyncLine -1", but -1 has extra logic in it, if you go from BeatsyncLine=1 to -1 which would be 0, it will do the very same thing as BeatsyncToggleOff.

**Comment by tkna91** [comment]
I think it is better to keep key input simple so that it basically works as indicated by the GUI and avoid unintended behavior when handled by external key macro tools, etc.
I don't have a problem with more key bindings, because the number of available key bindings can be increased by using external tools, for example, "If you hold down `Tab` for more than 500ms, it will function as `Shift+Ctrl+Alt+Meta`".
That said, this is your tool, so its behavior is ultimately determined by you.
If you are convinced that the behavior is more convenient for you, then no problem.
Even if the behavior is somewhat quirky to me, I find it much more important and appreciated to have them available in key bindings. The scripts are probably not obfuscated with bytecode, etc., so that part could be changed by me to suit my needs.

**Comment by esaruoho** [comment]
@tkna91  well, if you feel strongly that -1 on 1 beatsyncline should not turn beatsync off, i can remove that feature.

i'm wondering if you have any other ideas for shortcuts around this theme that you came in with, or should we call it a day and i just put the current code in and you have a look at how it works for you? i'm open to adding anything, as long as it's available from the api.

**Comment by tkna91** [comment]
> well, if you feel strongly that -1 on 1 beatsyncline should not turn beatsync off, i can remove that feature.

Thanks. In the meantime, I would like to try it out and then think about it. There may be something I am missing.

Wouldn't Finetune be a semitone at 100? If so, maybe the following values should be 10 each.

- Selected Sample Finetune +12
- Selected Sample Finetune -12

Also, I did some searching and can't seem to find the following API. Perhaps it has to be handled in some way that is not via the API, but I am not sure. I think we can put this on hold for now.

- Beatsync [T] button

> i'm wondering if you have any other ideas for shortcuts around this theme that you came in with, or should we call it a day and i just put the current code in and you have a look at how it works for you? i'm open to adding anything, as long as it's available from the api.

Thanks. The other thing I would like to have now is the ability to assign the pitch bend of a pit modulation to the pitch bend of a virtual keyboard. I really wish it were enabled by default in Renoise, but it is not, so it would make my work easier if I could set this assignment by default when I create an instrument, or if I could set it via key bindings. I will write another issue if necessary for you.

Screencast with audio:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/72a8ad5d-def0-4308-b94a-f98d2518cfde

**Comment by esaruoho** [comment]
@tkna91 hi i hope to soon build you a version for this and it'll just be the xrnx and you can run it and see what you think.

**Comment by tkna91** [comment]
@esaruoho Yes, how can I check? Is it committed or uploaded somewhere?

**Comment by esaruoho** [comment]
> @esaruoho Yes, how can I check? Is it committed or uploaded somewhere?

[org.lackluster.PakettiM1.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/13789418/org.lackluster.PakettiM1.xrnx.zip)
try this. remove the .zip from the end and it might be the xrnx. i'm not sure.
or take the xrnx and place it into your Tools folder.

**Comment by esaruoho** [comment]
```This can be done by dragging the folder onto the running Renoise window. ```

so drag the folder into a Renoise window.

**Comment by esaruoho** [comment]
> @esaruoho Yes, how can I check? Is it committed or uploaded somewhere?

[org.lackluster.PakettiM1_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/13789435/org.lackluster.PakettiM1_V3.54.xrnx.zip)

unzip this and doubleclick. let me know how it works.

**Comment by tkna91** [comment]
I extracted it and did `renoise *.xnrx` and it loaded. Thanks. I will check it.

**Comment by tkna91** [comment]
It is very convenient to be able to transpose samples with a computer keyboard!

screencast with audio:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/75b41497-ea58-4436-8126-cb43b733926d

**Comment by tkna91** [comment]
I am using this.
https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/13789435/org.lackluster.PakettiM1_V3.54.xrnx.zip

Setting Beatsync to 0 seems to cause an error.
screencast with audio:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/6dd978f2-cc15-4d4d-9a25-2d48af08ccbd

It would be easier if Beatsync were turned off when Beatsync is set to 0 so that multiple key bindings do not have to be assigned, but I still think it would be simpler and easier to understand if Beatsync is not set to stop when set to 0.


While operating, I thought it might be useful to have keybindings that halve and double the value of Beatsync so that it can be adjusted just the right size.

**Comment by tkna91** [comment]
As you mentioned, it would be useful to add the following sets (toggles) as well.

- Set to Beatsync ON + Repitch
- Set to Beatsync ON + Time-Stretch Percussion
- Set to Beatsync ON + Time-Stretch Texture

I think it would be good to keep the original individual behaviors as well, as it would ensure reliable operation in the event of automation, etc.

**Comment by tkna91** [comment]
The following probably refers to raw values, not dB, but `0.01` each, right?
I am a little confused, but I think it is good if there is no other appropriate wording.
- Set Selected Sample Volume +0.01
- Set Selected Sample Volume -0.01

**Comment by tkna91** [comment]
I have checked the following in a simplified manner. Other than the above, I think everything is fine.

- Set Selected Sample Interpolation to 1 (None)
- Set Selected Sample Interpolation to 2 (Linear)
- Set Selected Sample Interpolation to 3 (Cubic)
- Set Selected Sample Interpolation to 4 (Sinc)
- Set Selected Sample Oversample Off
- Set Selected Sample Oversample On
- Set Selected Sample Oversample On/Off
- Set Selected Sample Autofade On/Off
- Set Selected Sample Autoseek On/Off
- Set Selected Sample NNA to 1 (Cut)
- Set Selected Sample NNA to 2 (Note-Off)
- Set Selected Sample NNA to 3 (Cortinue)
- Set Selected Sample Mute Group to 0 (Off)
- Set Selected Sample Mute Group to 1
- Set Selected Sample Mute Group to 2
- Set Selected Sample Mute Group to 3
- Set Selected Sample Mute Group to 4
- Set Selected Sample Mute Group to 5
- Set Selected Sample Mute Group to 6
- Set Selected Sample Mute Group to 7
- Set Selected Sample Mute Group to 8
- Set Selected Sample Mute Group to 9
- Set Selected Sample Mute Group to A
- Set Selected Sample Mute Group to B
- Set Selected Sample Mute Group to C
- Set Selected Sample Mute Group to D
- Set Selected Sample Mute Group to E
- Set Selected Sample Mute Group to F
- Set Selected Sample Finetune +1
- Set Selected Sample Finetune +10
- Set Selected Sample Finetune -1
- Set Selected Sample Finetune -10
- Set Selected Sample Finetune 0
- Set Selected Sample Panning +0.01
- Set Selected Sample Panning -0.01
- Set Selected Sample Panning 0.0 (Left)
- Set Selected Sample Panning 0.5 (Center)
- Set Selected Sample Panning 1.0 (Right)
- Set Selected Sample Volume +0.01
- Set Selected Sample Volume -0.01
- Set Selected Sample Volume Reset (0.0dB)
- Set Selected Sample Loop 1 (Off)
- Set Selected Sample Loop 2 (Forward)
- Set Selected Sample Loop 3 (Backward)
- Set Selected Sample Loop 4 (PingPong)
- Set Selected Sample Loop Release On/Off
- Set Selected Sample Beatsync 1 (Repitch)
- Set Selected Sample Beatsync 2 (Time-Stretch Percussion)
- Set Selected Sample Beatsync 3 (Time-Stretch Texture)
- Set Selected Sample Beatsync Line (+1)
- Set Selected Sample Beatsync Line (-1)
- Set Selected Sample Beatsync On/Off

**Comment by esaruoho** [comment]
> Setting Beatsync to 0 seems to cause an error. screencast with audio:

interesting. which version of Renoise are you using? i'll look at this a bit more.

**Comment by esaruoho** [comment]
> The following probably refers to raw values, not dB, but `0.01` each, right? I am a little confused, but I think it is good if there is no other appropriate wording.
> 
> * Set Selected Sample Volume +0.01
> * Set Selected Sample Volume -0.01

they refer to db as that is what is available

**Comment by esaruoho** [comment]
> As you mentioned, it would be useful to add the following sets (toggles) as well.
> 
> * Set to Beatsync ON + Repitch
> * Set to Beatsync ON + Time-Stretch Percussion
> * Set to Beatsync ON + Time-Stretch Texture
> 
> I think it would be good to keep the original individual behaviors as well, as it would ensure reliable operation in the event of automation, etc.
> 
> EDIT: No, `Set Selected Sample Loop 1-4` is also Toggle, so maybe it would be better to unify it with Toggle. As for me, either is fine.

but i thought i did it like that already.
can you specify very clearly, one item per line, what you want and what you want it to do and i'll make them for you

**Comment by tkna91** [comment]
> > Setting Beatsync to 0 seems to cause an error. screencast with audio:
> 
> interesting. which version of Renoise are you using? i'll look at this a bit more.

My environment is as follows
- OS: Arch Linux x86_64
- Kernel: 6.6.9-arch1-1
- WM: sway
- renoise 3.4.3-1

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/ce6f4d56-4320-4db3-8e1d-38a77ab8817e)

Dialog when an error occurs

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/d37cb51b-9466-444c-842d-cf8dad5752c7)

**Comment by esaruoho** [comment]
> > > Setting Beatsync to 0 seems to cause an error. screencast with audio:
> > interesting. which version of Renoise are you using? i'll look at this a bit more.
> My environment is as follows

I took a look at my code and yes, it outputs 0 instead of just turning the beatsync off. i'll fix it and then try and see what the rest of your feature requests were about :)

**Comment by esaruoho** [comment]
ok so now it works like this: when going from 1 to 0, it leaves the beatsyncline amount to 1, but turns beatsync off. and if you then do a +1, it sets beatsync on, and beatsyncline amount is set to 2.

**Comment by esaruoho** [comment]
> As you mentioned, it would be useful to add the following sets (toggles) as well.
> 
> * Set to Beatsync ON + Repitch
> * Set to Beatsync ON + Time-Stretch Percussion
> * Set to Beatsync ON + Time-Stretch Texture
> 
> I think it would be good to keep the original individual behaviors as well, as it would ensure reliable operation in the event of automation, etc.

so you would like to have a separate set of shortcuts for repitch, percussion, texture without beatsyncON, and a separate set of shortcuts for repitch,percussion,texture with BeatsyncON? can do.

**Comment by esaruoho** [comment]
done. i'm now trying to see what else there is in this thread since it's quite long :)

**Comment by tkna91** [comment]
> so you would like to have a separate set of shortcuts for repitch, percussion, texture without beatsyncON, and a separate set of shortcuts for repitch,percussion,texture with BeatsyncON? can do.

Currently, the following are available. I think it is OK to leave this as it is without any toggle operation.
- Set Selected Sample Beatsync 1 (Repitch)
- Set Selected Sample Beatsync 2 (Time-Stretch Percussion)
- Set Selected Sample Beatsync 3 (Time-Stretch Texture)

In addition, I would be happy if you could add the following new items.
- Set Selected Sample Beatsync On/Off 1 (Repitch)
- Set Selected Sample Beatsync On/Off 2 (Time-Stretch Percussion)
- Set Selected Sample Beatsync On/Off 3 (Time-Stretch Texture)

**Comment by esaruoho** [comment]
> The following probably refers to raw values, not dB, but `0.01` each, right? I am a little confused, but I think it is good if there is no other appropriate wording.
> 
> * Set Selected Sample Volume +0.01
> * Set Selected Sample Volume -0.01

0.01 is the minimum amount that can be added and/or removed. that's why it's +0.01 or -0.01.. and no it's not +0.01dB or -0.01dB, instead +0.086dB or -0.087dB - and if you use the up/down buttons in Renoise, they add 0.100dB or remove -0.100dB. so this is slightly more precise.

**Comment by tkna91** [comment]
> 0.01 is the minimum amount that can be added and/or removed. that's why it's +0.01 or -0.01.. and no it's not +0.01dB or -0.01dB, instead +0.086dB or -0.087dB - and if you use the up/down buttons in Renoise, they add 0.100dB or remove -0.100dB. so this is slightly more precise.

I understand. I think it's fine as it is.

**Comment by esaruoho** [comment]
> > so you would like to have a separate set of shortcuts for repitch, percussion, texture without beatsyncON, and a separate set of shortcuts for repitch,percussion,texture with BeatsyncON? can do.
> 
> Currently, the following are available. I think it is OK to leave this as it is without any toggle operation.
> 
> * Set Selected Sample Beatsync 1 (Repitch)
> * Set Selected Sample Beatsync 2 (Time-Stretch Percussion)
> * Set Selected Sample Beatsync 3 (Time-Stretch Texture)
> 
> In addition, I would be happy if you could add the following new items.
> 
> * Set Selected Sample Beatsync On/Off 1 (Repitch)
> * Set Selected Sample Beatsync On/Off 2 (Time-Stretch Percussion)
> * Set Selected Sample Beatsync On/Off 3 (Time-Stretch Texture)

so like this
<img width="340" alt="Screenshot 2024-01-12 at 16 19 50" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/601841e5-bfd6-4342-901a-cd0b0678089c">

**Comment by tkna91** [comment]
> done. i'm now trying to see what else there is in this thread since it's quite long :)

> While operating, I thought it might be useful to have keybindings that halve and double the value of Beatsync so that it can be adjusted just the right size.

This is a bit of an odd expression and may need to be considered separately, but it would be useful if the value could be a power of the nearest 2.
- Set Selected Sample Beatsync Line (near+2^n)
- Set Selected Sample Beatsync Line (near-2^n)

If the current Beatsync value is 13, the following will set it to 16.
- Set Selected Sample Beatsync Line (near+2^n)

When the current Beatsync value is 13, the following will result in 8.
- Set Selected Sample Beatsync Line (near-2^n)

https://en.wikipedia.org/wiki/Power_of_two

**Comment by esaruoho** [comment]
> > done. i'm now trying to see what else there is in this thread since it's quite long :)
> 
> > While operating, I thought it might be useful to have keybindings that halve and double the value of Beatsync so that it can be adjusted just the right size.
> 
> This is a bit of an odd expression and may need to be considered separately, but it would be useful if the value could be a power of the nearest 2.
> 
> * Set Selected Sample Beatsync Line (near+2^n)
> * Set Selected Sample Beatsync Line (near-2^n)
> 
> If the current Beatsync value is 13, the following will set it to 16.
> 
> * Set Selected Sample Beatsync Line (near+2^n)
> 
> When the current Beatsync value is 13, the following will result in 8.
> 
> * Set Selected Sample Beatsync Line (near-2^n)
> 
> https://en.wikipedia.org/wiki/Power_of_two

i get what you're saying. sounds like something like "set selected sample beatsync line to nearest even number (up)" and "set selected sample beatsync line to nearest even number (down)". i'm not 100% sure how to do this, it's just a bunch of math really, but it surely can be done. i'll think about it. so this is the only thing that's left anymore, right?

**Comment by tkna91** [comment]
> i'll think about it. so this is the only thing that's left anymore, right?

I think the following is all that is left, including that.

- Do not turn off Beatsync when the value of Beatsync is less than 1
- Assign pitchbend to virtual keyboard pitchbend
- set selected sample beatsync line to nearest even number (up)
- set selected sample beatsync line to nearest even number (down)

Shall I create a separate issue for clarity?
Other than that, I think we can test it since we are discussing it here.

**Comment by tkna91** [comment]
Apart from my newly written issue, I believe my request here has already been fulfilled.
I would appreciate a release or test release.

**Comment by esaruoho** [comment]
> > i'll think about it. so this is the only thing that's left anymore, right?
> 
> I think the following is all that is left, including that.
> 
> * Do not turn off Beatsync when the value of Beatsync is less than 1
> * Assign pitchbend to virtual keyboard pitchbend
> * set selected sample beatsync line to nearest even number (up)
> * set selected sample beatsync line to nearest even number (down)
> 
> Shall I create a separate issue for clarity? Other than that, I think we can test it since we are discussing it here.
> 
> EDIT: I have summarized mine below. This will clear things up.

hi, please open a new ticket for these. and in the new ticket, please explain in some detail what `Assign pitchbend to virtual keyboard pitchbend` means. 

I'm currently setting up a new setup of Renoise and Paketti, on a new machine, so forgive me the delays. But a new delay would sound good. oh, you created them already, thanks!
