### ISSUE TITLE
Save to Logic / Ableton Live Smart Folders user-preferences / configuration

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#161]
need these to be set by preferences, and user-configurable:

| Global             | Save All Samples to Logic Smart Folder     |             |    X    |            |              |
| Global             | Save All Samples to Live Smart Folder      |             |    X    |            |              |
| Instrument Box     | Save All Samples to Logic Smart Folder     |             |         |     X      |              |
| Instrument Box     | Save All Samples to Live Smart Folder      |             |         |     X      |              |

**Comment by esaruoho** [comment]
ok, this is already getting better. just needs a GUI for this.

**Comment by esaruoho** [comment]
by better i mean that i cleaned it up like this:
<img width="656" alt="Screenshot 2024-06-12 at 10 56 38" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/d3f2dea8-2494-4d5c-a250-bfc4f8648db4">

**Comment by untilde** [comment]
Bug report:

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/20494933/c0f93080-b49e-4d73-8a65-408fab01bd3b)

It seems like this function is pointing to your user location (/users/esaruoho/...") instead of a local one.

Maybe place a "Smart Folders location" setting in the Preferences menu OR pop out a window to select the destination?

**Comment by esaruoho** [comment]
@untilde yrp i will make it into a preference. Just been put on the back burner a lot. I thought about it last night and its gonna be in the AppSelection gui as extra slots.

**Comment by esaruoho** [comment]
i'm going with 3 smartfolder folders and incorporating it into AppSelection.

**Comment by esaruoho** [comment]
<img width="911" alt="Screenshot 2024-06-21 at 15 17 42" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/6b314b15-da07-4660-a154-80d5c29efa87">
