### ISSUE TITLE
pause 0g01 when slicing samples

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#183]

**Comment by untilde** [comment]
I was about to report this.

When dealing with slices 0G01 will insert a new track for each added slice:

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/20494933/016baa74-428e-4b09-af2a-34c2d2d250c0)

**Comment by esaruoho** [comment]
fixed
