### ISSUE TITLE
Set Selected Sample Beatsync Line (Power of 2 immediately above/below)

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#20]
(Derived from #16)

Function to double/halve the Beatsync
The way the value transitions looks like it should be the same as the function below. (512 if an upper limit setting is needed)

- Double EditStep
- Halve EditStep

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/87e609ac-f483-493b-99d0-8a33a0c6b9e0)

screencast:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/bdc8011d-4e6d-446f-ad4a-2551916183b4

Form of value transition from 13:

- Double: 13, 26, 52, 104, 208, 416, 512
- Halve: 13, 6, 3, 1

**Comment by tkna91** [comment]
After thinking about it, I realized that the requirements are different.
The value of Beatsync must be a power of 2 to loop at the right place.
It would be better to transition to the nearest power of 2 that we were talking about before.

Form of value transition from 13:

- Set Selected Sample Beatsync Line (Power of 2 immediately above): 13, 16, 32, 64, 128, 256, 512
- Set Selected Sample Beatsync Line (Power of 2 immediately below): 13, 8, 4, 2, 1

**Comment by tkna91** [comment]
The problem is that such a name is too long to be displayed on the Preferences screen. Perhaps a native English speaker could come up with a good name, but it is a bit difficult for me.

(possibly wrong) random idea:

- Set Selected Sample Beatsync Line (near 2^n above)
- Set Selected Sample Beatsync Line (near 2^n below)
- Set Selected Sample Beatsync Line (+ near 2^n)
- Set Selected Sample Beatsync Line (- near 2^n)

**Comment by esaruoho** [comment]
hi @tkna91 
<img width="350" alt="Screenshot 2024-04-07 at 19 15 08" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/9012f353-8503-465d-8d6b-b7ec2ff8a38d">

please check if this works for you. please give me some feedback and if there's something that needs fixing.
https://github.com/esaruoho/org.lackluster.Paketti.xrnx/releases/tag/20240407171628

also please comment if this url above actually had a functioning zip you can easily download. cos if it does, great!!

**Comment by esaruoho** [comment]
sorry, that release was broken, but try this one:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/releases
the top one. do let me know if power of two above power of two below works.

**Comment by tkna91** [comment]
Yes, seems to work very well!
Thanks!
Screencast: 


https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/c3544acc-fb5a-4487-bf2e-b9c0dd0f4aa0
