### ISSUE TITLE
FT2: Selected Instrument Note Transpose (Instrument-based Note Transpose)

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#219]
<img width="584" alt="Screenshot 2024-07-04 at 9 33 27" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/25032b59-8224-4e92-b65e-e30065606482">

**Comment by esaruoho** [comment]
so a tentative name would be
Transpose +1/-1/+12/-12 for Selected Instrument in Selection/Track

**Comment by dmt-hub** [comment]
maybe these 2 blocks (instead of current instrument & all inst) -> TRACK & SELECTION

**Comment by esaruoho** [comment]
`current inst / all inst / track / selection`
