### ISSUE TITLE
Switching the output destination of the current track with a key

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#22]
In a workflow where you are creating tracks during a live show and want to use `Output01 Left/Right`assigned to the Renoise master channel as monitor outputs and `Output02 Left/Right` as outputs to the main floor, it would be useful to be able to switch between them using shortcut keys.
(I am surprised that this function is not standard.)

I think the following output destinations that can be key-assigned would be sufficient.

- Master
- Output 01 Left/Right
- Output 02 Left/Right
- Output 03 Left/Right
- Output 04 Left/Right
- Output 05 Left/Right
- Output 06 Left/Right
- Output 07 Left/Right
- Output 08 Left/Right

Screenshot:
![20240216-231447_screenshot](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/a8464fd2-40e3-4533-b52a-0e67425efe79)

**Comment by esaruoho** [comment]
Wonderful idea. I will look into it. Thanks for continually posting suggestions, I really appreciate it a great deal

**Comment by esaruoho** [comment]
ok i'm trying to figure this out now. ..
could it be that we're talking about
```
renoise.song().tracks[].available_output_routings[]
  -> [read-only, array of strings]
renoise.song().tracks[].output_routing, _observable
  -> [string, one of 'available_output_routings']
```

? then the issue, i think, is, that any soundcard will have a different set of available_output_routings.

so i could in theory deliver you "0, 1, 2" and let's leave it at that, but you'd need to know that 1 = output 01 left right and 2 = output 02 left right.

if you would be able to handle the knowledge yourself, i.e. "don't try to press something that doesn't exist" - then i could maybe write something that works like this

- first shortcut outputs the amount of available channels (either to Scripting Editor Terminal, or as a Dialog GUI visible to the user)
- second-to-x-amount-of-shortcuts deliver "Master" ... "last channel available on soundcard".

Btw, the more i think about this, and what you're asking for, this is exactly what i'd like to do, i.e. i would love to be able to audition stuff to headphones, before i drop it to the main PA. this suggestion of yours would deliver it.

so i'll see if i can build these easily.

**Comment by esaruoho** [comment]
<img width="296" alt="Screenshot 2024-03-31 at 23 47 01" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/41ed952b-2f1b-402a-a9fb-bb566e78315e">

**Comment by esaruoho** [comment]
i'm now experimenting with this. but i can only really use it after i am at my officespace with a soundcard with multiple outputs. @tkna91 do let me know if you wanna give this a try?
<img width="333" alt="Screenshot 2024-04-01 at 0 15 56" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/775f15fa-5433-41b7-bb50-ea94bad9309b">

**Comment by tkna91** [comment]
I'd like to give it a try, zip file or otherwise, but commit it and I'll clone it and check it out.
You can do whichever you are comfortable with.

**Comment by esaruoho** [comment]
ok, unfortunately, this is not trivial at all. see, they all seem to be called something other than what is expected, i.e. i can't do "0" ... "16", i need to start with "Master" and then " 1 & 2" (i kid you not, there needs to be a space at the start).
so i'm gonna need to look at this at the officespace and see what kindsa output names there are for my RME Fireface UCX soundcard.

so before i can make it work, i just need to make sure it _can_ work and _how_ it works.

**Comment by esaruoho** [comment]
ok, i have some sort of weird "dynamic method of creating shortcuts based on available outputs" and it seems to work. but i can only test with `"Master"` and `" 1 & 2"` so I'll have to wait till I get access to soundcard to be able to see what actually happens.

It seems promising. here's an example.

<img width="338" alt="Screenshot 2024-04-01 at 22 14 45" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/6fbcec5c-c5c6-499c-a3a3-fbdd3703c94f">

if it works with multiple outputs, i'll make a zip for you with the newest tweaks.

**Comment by esaruoho** [comment]
so, i have this dialog that now outputs the available channels. that should help somewhat.

<img width="379" alt="Screenshot 2024-04-01 at 22 33 32" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/bcbbe0f1-91bb-417b-8312-b5cdb84704b8">

the dialog reads the current-track-selected-routing before displaying the dialog. hopefully i can try this out tomorrow with a multi-channel soundcard and see what happens.

**Comment by esaruoho** [comment]
@tkna91 let me know how this goes for you:
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/14828106/org.lackluster.Paketti_V3.54.xrnx.zip)

**Comment by esaruoho** [comment]
reopening since the code that i was helped with, breaks startup of renoise, loses all shortcuts you've defined for Paketti, and makes sure Paketti shortcuts are not there. i need to fix this properly.

**Comment by esaruoho** [comment]
@tkna91 let me know how this goes for you - this should fix the issue with losing shortcuts and getting an error at startup on renoise
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/14833415/org.lackluster.Paketti_V3.54.xrnx.zip)

**Comment by tkna91** [comment]
Tested the shortcut keys.
Seems to be working as expected!
Looks very good. Thanks!

Screencast-1:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/7b97074f-0ed8-4eeb-9251-3466b2461098

Screencast-2:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/b832bf6a-958f-4388-a787-b6118eea74b5

**Comment by tkna91** [comment]
> Ideally i'd like to change the order altogether but I'm not a 100% sure how to do it.

I am indeed wondering what the sort order is based on.
At any rate, since it works fine, I think we can release it publicly and announce it on the forum.
I think everyone would be pleased!

**Comment by tkna91** [comment]
Yeah, but there seems to be a problem when saving the project.

Screenshot:
![20240402-195305_screenshot](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/5c50f8d1-8ee0-4b17-82da-ab26f4e89f7b)

Screencast:


https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/9a168cf4-9f19-4ca8-a8f8-f7524a639d0e

**Comment by esaruoho** [comment]
haa, thanks. i'll need to look at it a bit. it seems that the shortcut generation is run every single time you open a song. that's no good. i'll have to see.
anyway, over here, with some inputs, i see this:
<img width="341" alt="Screenshot 2024-04-02 at 13 56 48" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/4d6d9d05-4a2a-46ab-b1c9-e88905d6bbd3">

**Comment by esaruoho** [comment]
ok, after i returned back home, where i most certainly don't have a Fireface UCX available, the channels were still there. so i need to figure out _how_ to do this properly. and what happens when you don't have channels available.

the easiest would be to nuke and re-create the shortcuts from scratch on every load and save - but that would mean that one needs to continually set the shortcuts again. that doesn't feel very good as an idea, @tkna91  - i'm sure you don't think that's a good idea either.

**Comment by tkna91** [comment]
Since it would be time-consuming to manage this in a configuration file, why not assign the unconditionally detected output names to "Output Routing 01," "Output Routing 02," etc., in order of name?
If there are unwanted outputs, we can disable them using the standard OS functions.

**Comment by esaruoho** [comment]
@tkna91 ok i've done it in the simplest possible way, dBlue on the Renoise forum helped with the logic a bit. i've removed the dynamic creation. now i just gotta tweak the code a bit so that it doesn't shoot errors on the console when you try to bind something that doesn't exist.
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/14854722/org.lackluster.Paketti_V3.54.xrnx.zip)

let me know how this works for you @tkna91

**Comment by tkna91** [comment]
I feel the following key assignment functions are needed.
- Set Selected Track Output Routing Master

This should eliminate the mis-numbering of Output Routing shortcut assignments as seen below.

Screencast:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/4a12b4ab-43b9-4220-be5e-5ed51a8975c9

**Comment by esaruoho** [comment]
@tkna91 
i guess you're trying to say that 01 to you should set the routing to output 1.. and "00" should be Master. and not "01" = Master, even though it's the first one. okay, sure, i get what you're saying and how it appears. that's an easy fix.

i guess we're hoping for this:
<img width="355" alt="Screenshot 2024-04-03 at 22 55 04" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/9802fc87-e69a-4d4f-8fc4-9ba34547ea91">

once you give this build the once-over, please leave further comments or ideas, or, if nothing further seems needed, please close the ticket :)
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/14858487/org.lackluster.Paketti_V3.54.xrnx.zip)

**Comment by tkna91** [comment]
Yes, it seems to be working fine!
Thanks!

Screencast: 

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/7f68fce7-e335-48b3-9792-26deb1565971
