### ISSUE TITLE
Switching the output destination of the MASTER track

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#242]
Recently I have been running and playing multiple Reonoise instances and a need has arisen for me to monitor the master of each instance with headphones while preparing the track content and output to the main floor when ready.

Screencast:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/83443041-f370-408a-bf0f-cbd0d9039327

I would like to request a master track only version of this one that you have done before.
https://github.com/esaruoho/org.lackluster.Paketti.xrnx/issues/22

Screenshot:

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/c59b81fc-0b3c-4c43-b6c0-d40152f57384)

I think this would be useful. What do you think?

**Comment by esaruoho** [comment]
I fully agree. It is a good idea.

**Comment by tkna91** [comment]
Tested with WIP version, no problems found. Thanks! This is useful!

**Comment by esaruoho** [comment]
<img width="370" alt="Screenshot 2024-07-10 at 22 46 28" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/691e9275-c174-4a27-b705-9cc9090eeb8c">
