### ISSUE TITLE
Add MIDI Mapping: Switching the output destination of the MASTER & CURRENT track

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#244]
MIDI mapping for #242
- Specify CC only (0-63)
- Specify a region of 0-127 for use with knobs and sliders
  * For 64 outputs
    * CC:0-63 for output:0-31
    * CC:64-127 for output:32-63

MIDI mapping for #22
- Specify CC only (0-63)
- Specify a region of 0-127 for use with knobs and sliders
  * For 64 outputs
    * CC:0-63 for output:0-31
    * CC:64-127 for output:32-63

**Comment by esaruoho** [comment]
i did it in a better way, i.e. the knob is mapped to the available output routings.
![midimapping for selected track output or master track output](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/02e9a0a8-b223-4f35-8333-1b32fe693fc4)

if you have 64 outputs, then you are able to move the knob from output 0 to output 64.
if you have 12 outputs, then 0...12 outputs only.

**Comment by tkna91** [comment]
marvelous!

**Comment by tkna91** [comment]
I also checked the MIDI mapping by CC number. No problem found. Thanks!

![image](https://github.com/user-attachments/assets/45cdcadc-82da-4e4e-9151-0b2d5a91dabb)

![image](https://github.com/user-attachments/assets/21e5033e-6bb9-4ce2-a5a7-ad5d95d4a78b)

![image](https://github.com/user-attachments/assets/96c48d90-9195-4686-8bb9-977fff2a3c5d)
