### ISSUE TITLE
Increase/Decrease/0.0db Master Volume & Set Selected Track Volume (0.0db)

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#257]
There does not appear to be a master volume adjustment as a standard feature.
The following track volume adjustments are available.

- Increase Volume
- Decrease Volume

However, there does not seem to be a key binding to `0.0db`.
So the following would be useful.

- Increase Master Volume (+0.1db)
- Decrease Master Volume (-0.1db)
- Master Volume (0.0db)
- Set Selected Track Volume (0.0db)

MIDI Mapping allows for pre-volume and post-volume adjustment, but I think just post-volume adjustment is sufficient for key bindings. It would be nice to have both if it is not too much trouble.
I think the adjustment interval should be `0.1db` as well as the volume adjustment of the track.

Screenshot:
![image](https://github.com/user-attachments/assets/87a3067e-1dfd-4a6c-9331-bd5af0145a93)

Screencast with audio:

https://github.com/user-attachments/assets/8e7c56ab-a3ba-4085-8b81-f4e2abab7ee0

**Comment by esaruoho** [comment]
Master Volume OFF / 0dB
Selected Track Volume OFF / 0dB have been done

**Comment by esaruoho** [comment]
0.1dB -0.1dB Master track has now been done.

**Comment by tkna91** [comment]
It seems that some fractions are not handled, but this is not a practical problem. Thanks!

https://github.com/user-attachments/assets/f5de6abe-49a1-4fa6-bf93-6cae2068dfa8
