### ISSUE TITLE
[TTS] Generate TTS by specifying the line numbers of the loaded text file

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#263]
It would be useful if TTS could be generated by specifying individual text separated by newlines by line number.

**Comment by tkna91** [comment]
It would be nice if we could specify a line number range with a From To slider, etc. and get multiple samples of TTS.
For example, if a list of text sentences from 1-100 lines is described, it would be possible to create 100 samples in a single operation.

**Comment by tkna91** [comment]
> esaruoho — 今日 16:37 @tkna wouldn't it be simpler to go "please add checkbox for "add to current instrument" in addition to "overwrite samples in selected instrument" 🙂
It would be useful to have a choice of outputs to individual instruments or drum kits.

**Comment by esaruoho** [comment]
<img width="394" alt="Screenshot 2024-09-15 at 2 52 54" src="https://github.com/user-attachments/assets/31041efe-5ce7-495a-8a61-f10c88db8173">
here's a which row.
it will default to 0. if you change to 1, 2, 3, 4, or "last row", it will set that.

please put the rest in another ticket
