### ISSUE TITLE
eSpeak: Create shortcut keys that work when the TTS window is active

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#264]
Below are ideas.
- Ctrl+Enter to "Generage Sample"
- Alt+Enter to "Generate Selection"
- Ctrl+R to "Refresh"

**Comment by esaruoho** [comment]
i would move the "Generate Specified Row" shortcut to the other eSpeak ticket, since it is a new feature

**Comment by tkna91** [comment]
`Create shortcut keys that work when the TTS window is active`, so I meant that you need a fixed shortcut key such as `Ctrl+R` that works when the TTS window is active. However, if you think about it, that key binding is not likely to be used very often, so if it seems a little difficult, please abandon it.

**Comment by esaruoho** [comment]
<img width="357" alt="Screenshot 2024-07-28 at 9 56 53" src="https://github.com/user-attachments/assets/314335fc-8c88-4385-91cb-e5173a8a76ca">

oh yes, the "catch it in dialog but have it do something else elsewhere". i'll try and see where the thread was where unless said about it. 

ok i think it's this
https://forum.renoise.com/t/overriding-renoise-shortcuts-while-on-a-lua-dialog/72811/2
and
https://forum.renoise.com/t/overriding-renoise-shortcuts-while-on-a-lua-dialog/72811/4

```
local my_handler = function(dialog, key_event) 
  -- check whatever shortcut you want here and do stuff
  rprint(key_event)
end

renoise.app():show_custom_dialog("my dialog", my_view, my_handler)
```

**Comment by esaruoho** [comment]
done
