### ISSUE TITLE
C0F C00 gater (trance gate tool)

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#268]
![image](https://github.com/user-attachments/assets/72f61653-d1a4-4b98-bda3-3c33a1d8dde8)

a trance gate tool.. by using the C fx-command - C0F (on)  C00 (off) where one can choose from different patterns or make a pattern in the tool - choose the length of the pattern - and then add that to a track in a pattern.

(make a pattern in the tool) for example by showing a step sequencer layout (if possible) and putting notes on it (ON) / no notes (OFF)

maybe also an option for randomizing a certain number of steps with the trance gate and then filling up the track with it

**Comment by esaruoho** [comment]
idea from @dmt-hub btw

**Comment by dmt-hub** [comment]
the gator is perfect now - thank you!!

**Comment by esaruoho** [comment]
Closing as done
