### ISSUE TITLE
Select Effect for Effect Column, randomly place Effect + random value across selected track

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#271]
Suggestion for a tool:

chose an FX from FX column - for example - gliding notes - then hit random - and it then randomly places that one fx on a track on certain  random places

random glides for example - so you can make a melody - open the tool - choose the glide FX - hit random until you hear cool glides on your melody that you like -> win!

**Comment by esaruoho** [comment]
@dmt-hub would this include, in a dropdown menu, all the pattern effects? and would both the placement (let's say `0G` and the value `00 to FF` be all randomized)? or do you want control over minimum + maximum effect value?

**Comment by dmt-hub** [comment]
@esaruoho yes that would be nice, selecting one of the pattern effects in the menu, and the ability to have control of min max effect value is also good. Placement of the effects also random.

**Comment by esaruoho** [comment]
Paketti CheatSheet Effect Command Dialog with Randomize
https://www.loom.com/share/978e659e038e432d873272b8a819b96c?sid=df8061c5-fef7-45a0-bb43-aa0333bbe66a

@dmt-hub let me know if this ticket can be closed?
