### ISSUE TITLE
Tortoise TTS integrated into Renoise - for using a custom voice of choice (sample of 10secs)

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#272]
Tortoise TTS can be used for TTS with a voice of choice - would be nice to have this inside a renoise tool.
(alert: needs GPU power)

documentation: 
https://github.com/neonbjb/tortoise-tts
https://docs.coqui.ai/en/latest/models/tortoise.html
https://henrywithu.com/how-to-train-your-own-voice-model-with-tortoise-tts/

**Comment by esaruoho** [comment]
@dmt-hub is this multiplatform (linux, macOS, Windows)?

**Comment by esaruoho** [comment]
"If you want to use this on your own computer, you must have an NVIDIA GPU."
^ this cuts Apple Silicon out of the mix if i understand correctly.
