### ISSUE TITLE
Expanded scales tool panel

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#279]
As renoise has not so many scales to choose from, we need an extension ->>

A tool which lets you choose a scale (from " extensive " list of scales - or lets you add a custom one by selecting notes on 12 pianokeys).

after selecting the scale - it only shows you the notes from the scale in that toolpanel (all octaves) - and can be used to enter the notes into patt editor (see AFX wishlist) or for easy reference.
the tool panel should maybe also show a small 12 note pianokeys on top with the scale notes highlighted for easy reference.

example -> ( https://www.looknohands.com/chordhouse/piano/ )

**Comment by esaruoho** [comment]
too big to do right now, will look at later
