### ISSUE TITLE
Paketti Theme Selector Improvements

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#283]
- [x] Ingest the whole Forum thread Themes to the Themes folder (well, mostly, drawing the line at 440+)
- [X] Add favorites with "Add to Favorites"
- [X] Remove favorites with "Remove Favorite"
- [x] Randomize Favorites button
- [X] Randomize All button
- [x] Save "What was last loaded" and show it as a theme name.
- [X] button for "Load Previous Theme" 
- [x] Open Themes path (works on macOS, what about Linux or Windows?)
- [x] Open theme folder with macOS Finder & Windows Explorer etc
- [x] Pick a selection (Favorites) for a secondary dropdown menu
- [x] Randomize Favorite Theme on startup checkbox
- [x] Randomize All Themes on Startup checkbox
- [x] Shortcut for Random Favorite
- [x] Shortcut for Random All
- [x] Shortcut for Paketti Theme Selector dialog open
- [ ] Detect Clock and set Morning Theme
- [ ] Detect Clock and set Nighttime Theme
- [ ] Detect Clock and set Afternoon Theme
- [x] Load Favorites (textfile)
- [x] Save Favorites (textfile)

**Comment by tkna91** [comment]
- [ ] Next Favorite
- [ ] Previous Favorite

**Comment by esaruoho** [comment]
from EatMe:

```
can you please add a text input:
search
for i, #themes
  if string.match( themes[i].name:lower(), search.text:lower() )
     --show themes[i]
  else
     --hide themes [i]
  end
end 
```

**Comment by esaruoho** [comment]
halting development for now until i can recharge by doing smaller things

**Comment by esaruoho** [comment]
<img width="567" alt="Screenshot 2024-08-21 at 22 51 12" src="https://github.com/user-attachments/assets/eb389a04-6225-4ab4-84ac-c442513ac051">

**Comment by esaruoho** [comment]
closing the rest of this as maybe (the time would be neat but uhh..)

**Comment by esaruoho** [comment]
<img width="982" alt="Screenshot 2024-10-23 at 0 07 51" src="https://github.com/user-attachments/assets/577e1a20-c111-4174-9558-a6c54a2a9870">

oh noes, AM/PM has been suggested years ago
