### ISSUE TITLE
Switch to one previous Focus/Show

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#289]
It is similar to Alt+Tab in Windows or Command+Tab in macOS, executed only once.
When executed, it switches the focus/window display before and after these. a form like Alt+Tab would be complicated because you would need to have many histories, but you only need two window/focus histories.
If it is not possible to have a window history, then just the focus is fine.

Screencast:

https://github.com/user-attachments/assets/49a86d8b-7959-4b3d-b7b2-b941e95bb891

**Comment by esaruoho** [comment]
i think this requires api stuff. @tkna91 can you post on the API feature request thread? :)

**Comment by tkna91** [comment]
Are you saying that there is no API to get where the current area of focus is?

**Comment by esaruoho** [comment]
@tkna91 yes, there is no api for that. at least it's not called "focus".

**Comment by tkna91** [comment]
Please let me know if there is something wrong and I will change it.
https://forum.renoise.com/t/the-api-wishlist-thread/29285/377

**Comment by esaruoho** [comment]
closing  this until there's an api update. i'll reopen if new version has api features that will make this possible
