### ISSUE TITLE
Jump to Previous/Next Group

### ISSUE THREAD

**Issue by icasiino** [esaruoho/org.lackluster.Paketti.xrnx#30]
I would like 2 keybinds that when pressed within the pattern matrix, pattern editor, and mixer, will select/highlight the previous or next group track if they exist. Some refer to group tracks as busses. For someone like me who has a huge default project of 240 tracks with many groups that are collapsed and expanded frequently, this would be a huge time saver. If possible, o would like the keybind to jump to the first track within the group and automatically expand said group track if it collapsed.

As for the the last question you asked on the Renoise website, yes, that is the keyboard velocity tracking I was speaking of, the one that resides in the Sampler tab, if a shortcuts existed i.e.

Enable Sampler Velocity Tracking 
Disabled Sampler Velocity Tracking

Enable Sampler Velocity Tracking ALL
Disabled Sampler Velocity Tracking ALL

This would be conducive to creating instruments of one's favorite chops and samples. Thanks so much for this awesome tool

**Comment by esaruoho** [comment]
@icasiino thanks for writing! One question about the Group stuff - what should happen if there is a Group within a Group?
<img width="336" alt="Screenshot 2024-04-21 at 22 46 29" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/64091d7d-06c4-4c81-a43d-1982ac4cefb6">

In a situation like this, would you still want the "Master Group" (the highest in the hierarchy) to be the one that is selected, and then the next "Master Group" - without focusing on the nested Groups?

---
Next, the Sampler Velocity Tracking - 
It seems it is possible to set the Min / Max (0...127) Velocity Tracking - and something about Clamp and Scale (Different Modes)

and also something like `Mappings velocity->volume and key->pitch options.`  and `Velocity range the mapping is triggered for.`  - are we specifically talking about setting Velocity Range 127...127 so no matter what, it will hit at full volume, (Disabled Velocity Tracking? would that work?) and then 0...127 for "Enabled Velocity Tracking", for either SelectedSample, or SelectedInstrument(=ALL)? 

I'm wondering about the usecase of this, could you provide a XRNI example for me as a zip, you can email it to esaruoho@icloud.com if that helps (if you want to keep it private). 

i'd generally love to understand more about this, and also the SliceStretching with BeatSync - as i was able to "kinda" get melodies out of drumloops by pitching them but maintaining the speed at which they hit, but I'm not sure I'm fully understanding what we're after. Do you also slice melodic loops and wish to have them hit at different notes? 

I'm hoping that with some back'n'forth between us, I'll be better able to understand what you're after, and then provide it, as the rest is just "onecycle this" "BeatSync that" "Percussion Stretch them" "BeatSync count increase/halve" - but I think if you give me some examples, and tell me what you're specifically after, I'll be able to work it all out for you.

This "pitched stuff within Slices" thing is very new to me.

**Comment by icasiino** [comment]
![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/167565561/c1cf71c0-025b-4872-8efe-3541e0a23e87)

Yes, I would like when the key is pressed to always jump to the lowest level of tracks. Now that I've thought about it. Maybe there should be another set of shortcuts:

Jump to previous track in group(always lowest level)

Jump to next track in group(always lowest level)

Jump to previous group master bus
Jump to next group master bus

**Comment by icasiino** [comment]
Okay and I will try to get my default project to you as well as a project with casiino stretch being used

casiino stretch was a function designed specifically for melodic sample slicing/chopping. I.E. serato sample.


Its function required the original sample to be beatsynced and it would calculate the beatsync lines of the slices based on the value of original sample. So by pressing one key after slicing one would have time synced slices

However I ran into a few flaws, being that depending on one's project lpb, which functions as resolution, the precision of the beginning and end of a sample, and length of the sample, the slices could still be out of sync slightly or too fast or too slow.

However I've downloaded the karate chop tool and I've come to understand that having the slices beatsync length based on the pattern length in the editor or any division of such is more optimal, as one wouldn't be required to beatsync the original sample at all. Also, IMO the percussion option sounds better in general regardless of the sample. However those options as well as mute group, NNA, etc wouldn't be required as an addition to Paketti, as it has these options already. A simple sync slices would suffice, but if you feel you'd like to aggregate all the functions as well that would benefit others with different workflows and remain in the spirit of the original casiino stretch 😊

options for sync slices could be:

sync slice
sync slice ALL

double sync length
double sync length ALL

halve sync length 
halve sync length ALL

And of course the beatsync length should be based on the pattern editor length, WITHOUT having to beatsync the original sample. And by being able to double and HALVE the speed of each slice one can reasonably slice and chop entire songs if desired.

Now, next I'm going to contact markblek because he has a tool that detects beats and slices samples by beats. I don't require all that, simply finding the first and last beat within a sample and deleting what comes before the first and after the fourth(before the next beat)would ensure that for most samples all slices would be in sync. It will never be perfect as there is way too much audio material for everything to work perfectly. But this ensures that most songs and sample packs, loops, etc could be sliced/chopped quickly.

**Comment by esaruoho** [comment]
> double sync length
> double sync length ALL 
> halve sync length
> halve sync length ALL

ahh, so this would be a double sync or halve sync per selected slice?

**Comment by esaruoho** [comment]
@icasiino i edited your title since your request is not only about jump next prev group.

**Comment by esaruoho** [comment]
i've split this ticket to multiple tickets so it's easier to maintain. @icasiino if you have the time, please hit #50 and #51 with more details.

**Comment by esaruoho** [comment]
ok i have a lister now that lists all the tracks. and it does differentiate if there's type 4. type 4 is Group.
now i'm trying to figure out how to move to next group based on "selected_track  -> find next track that is type 4".

**Comment by esaruoho** [comment]
ok.
i have shortcuts for this. and midimappings.
<img width="326" alt="Screenshot 2024-05-13 at 12 37 47" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/efb20ddd-788b-44a0-bcaa-5c2a5b5eb000">
<img width="328" alt="Screenshot 2024-05-13 at 12 40 07" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/004c9949-54f3-4eeb-b97d-a42e3a2932e1">

@icasiino would you like a knob that lets you cycle through all the Groups? that would be trivial to do.
i'll set another ticket and close this one.
the ticket for midiknob will be #98

**Comment by esaruoho** [comment]
and the "lowest group" & "highest group" is logged as #99
