### ISSUE TITLE
eSpeak new features

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#307]
- [x] Generate Specified Row
- [x] Shift+Enter to "Generate specified row"

(from #264 )

- [x] randomize for language + voice + settings
- [x] randomize for textfield content, so random string of x length
- [x] Randomizer consonants
- [x] Randomize vowels
- [x] add render to current instrument 
- [x] Normalize Volume

**Comment by tkna91** [comment]
I am looking forward to the following features
> - Generate Specified Row
> - Shift+Enter to "Generate specified row"

In this case, it would be useful if line numbers could be displayed in the text field. If this is difficult or impossible, it is not required.

**Comment by esaruoho** [comment]
I've added the Randomize Settings - it will randomize Language, Voice, Word Gap, Pitch Capitals, Pitch, Speed.
<img width="389" alt="Screenshot 2024-09-01 at 22 02 11" src="https://github.com/user-attachments/assets/5c6a066b-654b-4487-9c3a-12b384d3a045">

**Comment by esaruoho** [comment]
have added normalize sample, so default volume is 03 and then normalized.

**Comment by esaruoho** [comment]
added randomize consonants and rnadomize vowels to the mix

<img width="388" alt="Screenshot 2024-09-01 at 23 03 41" src="https://github.com/user-attachments/assets/d2a59359-d5ea-4f98-9f8c-67462cd3ec83">
<img width="392" alt="Screenshot 2024-09-01 at 23 03 46" src="https://github.com/user-attachments/assets/e1138d40-4d65-44bc-a83c-e60437eb196f">

**Comment by esaruoho** [comment]
<img width="394" alt="Screenshot 2024-09-01 at 23 07 32" src="https://github.com/user-attachments/assets/7bfc8387-cc4c-4c22-be6e-c39b144230b6">

**Comment by esaruoho** [comment]
as per what @tkna91 specified elsewhere:
```
Useful. I would like to see the ability to run
one line at a time, separating the text with
a line break and specifying a range for each line!
For a text with 10 lines, specifying 3-8 lines
would generate 6 samples.
```

**Comment by esaruoho** [comment]
<img width="349" alt="Screenshot 2024-09-17 at 23 49 54" src="https://github.com/user-attachments/assets/1364ea8c-6e83-4cb2-91a1-a1b2e6bdbef7">

**Comment by esaruoho** [comment]
moving this to elsewhere:
```
 preferences so that you can have your ESC to close the dialog, and bleed shortcuts into eSpeak, but for me, i want to disable all of them. so "dialogShortcuts+Focus = TRUE" -> your method, "dialogShortcuts+Focus = FALSE" -> my method.
```

**Comment by esaruoho** [comment]
<img width="390" alt="Screenshot 2024-09-27 at 13 53 23" src="https://github.com/user-attachments/assets/5cb61dfb-cf4c-479a-b91d-8716c75c2f73">
