### ISSUE TITLE
[Effect Command CheatSheet] Add option `Overwrite no value with 0000`

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#312]
Feel free to change the wording.
It makes randomization a bit more complicated.
As a variation of the randomization, it would be nice to have an option to not overwrite with 0000 what would be spaces when not Fill All. Conversely, it would be a “overwrite no value with 0000” option.

https://github.com/user-attachments/assets/31baad17-d449-4561-a725-96607c6f5212

**Comment by esaruoho** [comment]
done

**Comment by tkna91** [comment]
Not exactly. It does not mean that the new randomization fills in the empty space, but that it does not do so where the new randomization overwrote it with 0000 in the previous version.
It is acceptable to overwrite with a value other than 0000. However, “nothing” should be written where there is an empty space.
By doing so, you can continue to overwrite it with another random value in a complex way.
In the version I just received, when there is no more free space, it stops being randomizable.
It is no longer possible to add other values from this state.
![20240730-143708_screenshot](https://github.com/user-attachments/assets/9011ce3e-3fe0-4d30-a626-1d049d471666)

Overwriting with a random value for the target is done. However, do not use 0000 and “write nothing” in its place. By doing so, the random value can be overlaid with the previous information remaining.
