### ISSUE TITLE
Investigate the possibility of using luarocks

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#314]
There is a lua package manager called luarocks, is anyone using this for Renoise Tools?
My imagination is that it would be possible to include downloaded lua files and include them directly in Tools. Of course, you would need to comply with the respective licenses, but basically, I think you can keep it open source and just indicate the credit.
https://luarocks.org/

**Comment by esaruoho** [comment]
@tkna91 please can you specify what the usecases / benefits here are? :)

**Comment by tkna91** [comment]
Basically, it allows you to find and download packages as shown below.
```
$ luarocks search csv

csv - Search results for Lua 5.4:
=================================


Rockspecs and source rocks:
---------------------------

csv
   1-1 (rockspec) - https://luarocks.org
   1-1 (src) - https://luarocks.org

csv2tensor
   0.2-0 (rockspec) - https://luarocks.org
   0.1-3 (rockspec) - https://luarocks.org
   0.1-2 (rockspec) - https://luarocks.org
   0.1-0 (rockspec) - https://luarocks.org

ftcsv
   1.3.0-1 (rockspec) - https://luarocks.org
   1.3.0-1 (src) - https://luarocks.org
   1.2.2-1 (rockspec) - https://luarocks.org
   1.2.2-1 (src) - https://luarocks.org
   1.2.1-1 (rockspec) - https://luarocks.org
   1.2.1-1 (src) - https://luarocks.org

lcsv
   1.1-1 (rockspec) - https://luarocks.org
   1.1-1 (src) - https://luarocks.org
   1.0-1 (rockspec) - https://luarocks.org
   1.0-1 (src) - https://luarocks.org

lua-csv
   1.1-1 (rockspec) - https://luarocks.org
   1.1-1 (src) - https://luarocks.org

pretty-csv
   1.0-0 (rockspec) - https://luarocks.org

streamcsv
   1.1.0-1 (rockspec) - https://luarocks.org
   1.1.0-1 (src) - https://luarocks.org
   1.0.0-1 (rockspec) - https://luarocks.org
   1.0.0-1 (src) - https://luarocks.org

thcsv
   1.0-1 (rockspec) - https://luarocks.org

tree-sitter-csv
   0.0.2-1 (rockspec) - https://luarocks.org
   0.0.2-1 (src) - https://luarocks.org
   0.0.1-1 (rockspec) - https://luarocks.org
   0.0.1-1 (src) - https://luarocks.org

$
$ luarocks download csv
$ ls -l
total 12
-rw-r--r-- 1 a a 9875 Jun 19  2014 csv-1-1.src.rock
$ file csv-1-1.src.rock
csv-1-1.src.rock: Zip archive data, at least v2.0 to extract, compression method=deflate
$ unzip csv-1-1.src.rock
Archive:  csv-1-1.src.rock
  inflating: csv-1-1.rockspec
   creating: lua-csv/
   creating: lua-csv/test-data/
 extracting: lua-csv/test-data/blank-line.csv
 extracting: lua-csv/test-data/header.csv
  inflating: lua-csv/test-data/embedded-quotes.csv
  inflating: lua-csv/test-data/embedded-newlines.csv
  inflating: lua-csv/LICENSE
 extracting: lua-csv/AUTHORS
  inflating: lua-csv/makefile
   creating: lua-csv/rockspecs/
  inflating: lua-csv/rockspecs/csv-1-1.rockspec
  inflating: lua-csv/README.md
   creating: lua-csv/lua/
  inflating: lua-csv/lua/config.ld
  inflating: lua-csv/lua/csv.lua
  inflating: lua-csv/lua/test.lua
$
```
The use of the source in this example can be found below.
https://github.com/geoffleyland/lua-csv

I am not sure how much we can use that within the framework of Renoise Tools, but I thought it would save development labor if it could be used by simply requiring it.

Of course, you must carefully check the LICENCE before you use it.
If you use the GPL, there are restrictions, such as the fact that you must use the GPL license for your own software.

**Comment by esaruoho** [comment]
i get it. yes, there are tools and libraries that can be added by luarocks. but what i'm looking for is a usecase. like, "this is what can be done" - i.e. "here's a specific usecase that can be accomplished by using luarocks"

**Comment by esaruoho** [comment]
i've labeled this with `maybe` since i can't figure out what the usecases are. closing for now.

**Comment by esaruoho** [comment]
ok so for instance luamidi might allow for conversion of imported midi to xml to renoise tracker data.
and maybe it'd allow the other way around too.
this is definitely in the `maybe` territory and once i am down to only have 10 or so issues on GitHub, i'll start looking into this, since this'll be a major can of worms and a big ol' rabbithole full of possibilities, i will probably be stuck in luarocks territory for months to years.
