### ISSUE TITLE
Add buttons next to volume,pan,delay,samplefx sliders, for randomizing current parameters for those subcolumns

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#316]
randomize parameters of existing, but don't write. 

change what's already there.

**Comment by esaruoho** [comment]
this means introducing a button next to all 5 sliders, and once shot, it will randomize min/max or between min/max.

**Comment by dmt-hub** [comment]
indeed, thats correct, it will then randomize the existing entries in the pattern, not add any new entries

**Comment by esaruoho** [comment]
<img width="613" alt="Screenshot 2024-09-24 at 9 06 13" src="https://github.com/user-attachments/assets/5e025ac7-cf62-4300-a246-39b7f7530547">
it looks terrible, but i've been fooling around with it. i wanna make it look better, and then ship it.

**Comment by esaruoho** [comment]
<img width="621" alt="Screenshot 2024-09-24 at 10 36 06" src="https://github.com/user-attachments/assets/ab853b61-28e0-40f3-9134-c52f1cc37818">

overall it looks better now
