### ISSUE TITLE
tool: name generator

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#321]
tool idea

name generator

option to add custom text file full of words

ability to choose random name -> consists of 1 word / 2 words / 3

randomly combines one of the words until one you like

option to start filename with date (for sorting purposes) -> 2024-07-30 - random trackname

Save as dialog

**Comment by dmt-hub** [comment]
would be cool to have the option if wanted to start each word with a Capital Letter (checkbox?)

**Comment by dmt-hub** [comment]
when you get your random name it would be nice to have the option to >> shift the placement of words around

**Comment by esaruoho** [comment]
<img width="626" alt="Screenshot 2024-08-02 at 13 46 50" src="https://github.com/user-attachments/assets/d9ae07ea-4962-4eaa-a0cd-16490e863a9b">
closed as done
