### ISSUE TITLE
`Beatsync On/Off 1-3` does not work as a toggle

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#33]
Beatsync On but not Off (doesn't seem to work as a toggle).

Screencast:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/c03cefc7-74d7-43d0-9e5e-19f7174a9c0a

Version:
`https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15138153/org.lackluster.Paketti_V3.54.xrnx.zip`

**Comment by esaruoho** [comment]
thanks i'll tweak it

**Comment by esaruoho** [comment]
@tkna91 
ok. i added some extra logic.
i.e. if BeatSync = On and Mode is NOT the mode you want, then maintain beatsync = on and change mode.
if beatsync = on and mode = is the shortcut you want, but you want to toggle it off, then maintain mode but turn beatsync off.
here's an updated version.
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15138319/org.lackluster.Paketti_V3.54.xrnx.zip)

**Comment by esaruoho** [comment]
if this now works as expected, please close the ticket :)

**Comment by tkna91** [comment]
Confirmed. It looks fine. Thanks!
