### ISSUE TITLE
Paketti track dater & titler improvements

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#337]
a small extension to go completely overboard:

- when finding cool titles it would be nice if these could be saved into one predefined .txt file

**Comment by esaruoho** [comment]
<img width="499" alt="Screenshot 2024-09-17 at 22 38 28" src="https://github.com/user-attachments/assets/752cc455-c8be-45b1-8b1f-672e49883d01">
