### ISSUE TITLE
Open Dialog, select sample, load pitchbend, add sample to first slot samplebuffer

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#34]
this is a tweak for making it easier to select a sample from the regular OS Open Dialog.

It:
Opens a Dialog
Lets you select a sample
Press OK
the Pitchbend Instrument is loaded
The selected sample is loaded

== a method for loading and having pitchbend-already-there instrument.

@tkna91 you might like this.

**Comment by tkna91** [comment]
Oh, that sounds good.
Perhaps the key point would be to use a file chooser for each OS, called from a lua function, to select a sample, and then perform any processing before or after that file is read.
Renoise's file chooser is rather difficult to use, so using the standard file chooser for each OS seems like a very good idea.

**Comment by tkna91** [comment]
It would be nice if we could set an arbitrary directory for file selection.
If we put a link (shortcut) there, it could be used universally.

**Comment by esaruoho** [comment]
> It would be nice if we could set an arbitrary directory for file selection.
> 
> If we put a link (shortcut) there, it could be used universally.

Could you be more specific and share more Details, @tkna91 ?

**Comment by esaruoho** [comment]
> It would be nice if we could set an arbitrary directory for file selection.
> 
> If we put a link (shortcut) there, it could be used universally.

Do you mean like "set default folder the OS file selection dialog always opens in"? If thats what u mean, it is a good idea and can be done. If u mean something else then please help me understand

**Comment by tkna91** [comment]
> Do you mean like "set default folder the OS file selection dialog always opens in"? 
 
That's right.

**Comment by esaruoho** [comment]
ok, when i created this issue, i already had most of it running.
but what isn't running, is, that the instrument is called "12st_Pitchbend Instrument", and the sample, when loaded, is called "Placeholder sample". Ideal situation is that the filename of the loaded sample is there in Instrument and in Sample slot. That's what I want.

The idea about Paketti Preferences having say, 4 or 8 different slots for paths, and the user being able to open the OS dialog in those folders with a shortcut, appeals to me a great deal. I really like the idea, and want to make it reality. I absolutely abhor the Renoise Disk Browser - it is hands down the most frustrating part in Renoise - apart from, of course, the Pattern Editor - unless if it has the Paketti shortcuts.

Thanks for providing the idea, @tkna91 . if you have any refinement ideas, i'd really appreciate hearing them.

**Comment by esaruoho** [comment]
btw, one really cool feature of the Pitchbend Loader is that it remembers which folder you were in previously. 

Anyway, I need to solve the instrument + sample naming issues now, before moving towards getting Preferences going for saving sample slots.

**Comment by esaruoho** [comment]
<img width="1209" alt="Screenshot 2024-04-27 at 23 30 58" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/6f4595c8-9346-4232-8294-d649b33f35b6">

instrument + sample naming issues are solved.

i've left an API request for opening the sample load prompt in a specific filepath. it doesn't seem to be supported.

**Comment by esaruoho** [comment]
this is what i'm working with right now:
https://www.loom.com/share/9a782bc664334f0c881ffa67b07195e0?sid=d68d74c8-7534-4fb6-8bcb-c069394ddf27

an additional thing that needs to be fixed - upon loading a sample, it should always end up in Sample Editor, not use the Paketti `F3` feature to "get to Sample Editor" - because of F3 having extra logic where "if you are in Sample Editor, go to Phrase Editor". so in the end, a sample should always be displayed.

**Comment by tkna91** [comment]
It would certainly be useful to be able to load individual drum instruments, etc. at once.
If multiple files are to be loaded at once, it would be nice to be able to enable Keyzones Drum Kit before loading.
![20240428-121205_screenshot](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/ac47e968-45a0-444c-b507-81d4ccab0b6f)

**Comment by esaruoho** [comment]
@tkna91 there can be two separate types of loading, drumkit multisample load for "samples in instrument", with drumkit enabling. but what i'm looking for is "load 30 samples, create 30 instruments". after i do that, then i can do the drumkit one.

**Comment by esaruoho** [comment]
@tkna91 if possible, please create a "DrumKit OS Loader with Pitchbend" ticket.

The single load one is here - give it a try:
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15141220/org.lackluster.Paketti_V3.54.xrnx.zip)

<img width="344" alt="Screenshot 2024-04-28 at 10 44 18" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/03586438-7d61-4139-9b36-530824c835a0">

**Comment by tkna91** [comment]
Maybe it's because it's Linux, but it looks like the following
- It will be Renoise's file chooser, not the OS's
- Error when canceling file chooser

![20240428-182430_screenshot](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/221dd141-941c-48bd-9c78-9a2e1482b7bc)

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/5515cd8c-78d9-4600-ac08-86b2a4dcdf96

**Comment by esaruoho** [comment]
@tkna91 ok, now we know what it says when nothing is selected. can you also select something instead and see what it says?

**Comment by esaruoho** [comment]
i have replicated the error when selecting nothing - i'll fix it and push a change.
but please let me know how it goes when you actually select a file.

**Comment by esaruoho** [comment]
the "didn't select anything, because user pressed Cancel" error is no longer displayed - fixed.

[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15142213/org.lackluster.Paketti_V3.54.xrnx.zip)

**Comment by esaruoho** [comment]
> Is it going to be difficult to use the OS standard file chooser for Linux? I wonder if the functions for file choosers in Renoise's API are not compatible with Linux?

i don't know. this is what linux serves. maybe it's a bug - could you raise it within the Renoise Forum in the Bug Forum?
https://forum.renoise.com/c/help-support-bugs/9

anyway, here's the "multiple file loader":
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15142316/org.lackluster.Paketti_V3.54.xrnx.zip)


and here are some videos + descriptions of what these do:

Paketti PitchBend Loader loads a selected sample using the available OS Explorer (macOS shows a Finder), you select a sample from the formats .wav .aif .aiff .flac and .mp3 (feel free to ping me at esaruoho@icloud.com if you need other formats), then it loads the +12st Pitchbend Instrument, names the Instrument in the Instrument Box and the Sample in the Sample Slot by the selected filename, and loads the sample. Then sets Autoseek=On, Autofade=On, Oversampling=On, Interpolation=Sinc and moves you to the Sample Editor so you can see what you just loaded. This evades the need for using the Renoise Disk Browser for finding a sample, as it is far quicker to use the macOS Finder (or Windows Explorer, I guess) to load content. (This also provides you with being able to drag a wavefile from another macOS Finder window, to the Paketti PitchBend Loader dialog, and pressing enter, and there you are with the processed sample)
https://www.loom.com/share/e9a950cc63cb4745a4aa4f332fa248fe?sid=4d6c53d3-b583-4202-952b-d291d207da54

Paketti PitchBend Multiple Sample Loader - does the same, but multiple files. Same processing for each file.
https://www.loom.com/share/338ed392087d4fee8588d7455bfe7e75?sid=258a95e3-02bd-449f-a3b9-74bcdb6f6f9e


<img width="337" alt="Screenshot 2024-04-28 at 16 47 33" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/5bcd3911-c0dc-46bb-b94b-a6d040d40845">

**Comment by esaruoho** [comment]
if you come across any issues with this, please create a new issue, @tkna91. closing this issue for now.

**Comment by tkna91** [comment]
`Single Sample Loader` may not be necessary
`Multiple Sample Loader` appears to be usable as a `Single Sample Loader`

**Comment by esaruoho** [comment]
@tkna91 yep, that's why there's this now:
<img width="366" alt="Screenshot 2024-05-24 at 13 22 10" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/3ed321c1-acf0-4d85-be88-3766cd729c87">
