### ISSUE TITLE
Stepper for Volume, Delay, Panning, 5 Macro knobs - print on effect columns? (macro knobs selectable)

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#340]
![afbeelding](https://github.com/user-attachments/assets/3ba96641-dffd-4369-9cdb-8bb9c9acf8be)

sliders to set volume / delay / panning for 8 (or even 16?) steps. 
ability to set looppoint (8 steps max in this case or 16?).  
set min / max value for randomize / randomize / receive / print.. oh, lets also add << >> SHIFT 
maybe even checkbox use only min & max value for randomize

nothing selected = fills whole pattern with it
selection = fills only selection

**Comment by dmt-hub** [comment]
I had another addition in mind, would it be possible to add another lane - where we can choose one of the macro knobs - for example the decay (from ADSR) 
or choose the filter cutoff

**Comment by esaruoho** [comment]
<img width="719" alt="Screenshot 2024-10-02 at 10 22 56" src="https://github.com/user-attachments/assets/f1dc6b12-30fa-472c-90cc-99e85f0071c8">

**Comment by esaruoho** [comment]
<img width="752" alt="Screenshot 2024-10-02 at 12 04 18" src="https://github.com/user-attachments/assets/f3d59cbc-6cc4-4382-90e9-f07971ab63a4">
