### ISSUE TITLE
Player Pro Note Selector additions

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#343]
would be cool when choosing note with playerpro note selector - if this valuebox was added to the dialog
![afbeelding](https://github.com/user-attachments/assets/4edea944-a28c-4220-b001-a1ed5dd0ae1f)

and a scales dropdown menu + key dropdown menu - when choosing certain scale & key it only shows the notes within that scale
![afbeelding](https://github.com/user-attachments/assets/2767637c-7a24-4033-807f-09b787d5361a)

when choosing custom scale - this option
![afbeelding](https://github.com/user-attachments/assets/3f3e8989-3f97-47cb-8481-5303a8d1088f)

**Comment by esaruoho** [comment]
moved into #389
