### ISSUE TITLE
When dragging & dropping many samples from Finder, open them as separate instruments

### ISSUE THREAD

**Issue by vsctmby** [esaruoho/org.lackluster.Paketti.xrnx#35]
When you drag & drop a sample on top of Renoise, it adds it as an instrument. When you do the same to many samples, it loads them as many samples on one instrument. 

How about asking if you want to load them as separate instruments?

**Comment by esaruoho** [comment]
hi @vsctmby 
i've created a shortcut that allows for opening a macOS Finder dialog which you can either drag files into, or select files from. each will be loaded as an instrument, with pitchbend +12st enabled, autofade, autoseek, interpolSinc, oversampling enabled, and the sample slot has the filename and the instrumentbox has the filename.

please let me know if this does what you want it to do, and if so, please close the ticket.

if there are bugs, let me know and i'll try to fix them.

https://www.loom.com/share/338ed392087d4fee8588d7455bfe7e75?sid=258a95e3-02bd-449f-a3b9-74bcdb6f6f9e
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15142290/org.lackluster.Paketti_V3.54.xrnx.zip)

**Comment by vsctmby** [comment]
![script_bug](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/18572312/87911f10-961e-45de-94eb-760c279e810a)

I tried to open 2 samples to empty instruments, this happened.

**Comment by esaruoho** [comment]
sounds like we need to get this working from the Windows side, since it works on macOS. i've sent you a debug mode version which should at least tell us if the selected sample paths are passed properly. @vsctmby

**Comment by esaruoho** [comment]
after some tweaks for windows, we got it working (single + multiple loader). so, closing ticket
