### ISSUE TITLE
randomly pick a saved device chain from chosen folder and place onto track

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#358]
a shortcut tool for this:
randomly pick a saved device chain from chosen folder and place onto track.

**Comment by dmt-hub** [comment]
default folder renoise/user library/device chains/

**Comment by esaruoho** [comment]
i've started work on this but from a different direction: just added a DeviceChains folder and added SimpleSend.xrnt there.

**Comment by dmt-hub** [comment]
should be used fresh track with no dsp fx on it.
maybe add warning when there are dsp on it - want to overwrite?
if nothing is on a track - go ahead without warning

**Comment by esaruoho** [comment]
![random device chain](https://github.com/user-attachments/assets/d2efdbc6-ddd8-4347-9423-114fa8b6084c)

feels like this closes it.
of course, you need to pick the folder yourself, it's currently hardwired to the ones in DeviceChains folder in Paketti.
