### ISSUE TITLE
shortcut to do a mini fade in/out on a sample

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#372]
shortcut to do a mini fade in/out on a sample (fade in & out at around 10 steps)

**Comment by esaruoho** [comment]
done, closing
<img width="1126" alt="Screenshot 2024-08-11 at 23 03 49" src="https://github.com/user-attachments/assets/a2df8157-a668-43b3-8a18-eb4a1c84a37a">
<img width="1120" alt="Screenshot 2024-08-11 at 23 04 06" src="https://github.com/user-attachments/assets/10741ee4-a971-47e6-b4a9-c0fd279c047e">
![image](https://github.com/user-attachments/assets/b49fc695-c98d-4951-b7d9-83c8fface78d)
![image](https://github.com/user-attachments/assets/18aecee9-dd47-43c7-bb03-4c41bf801d5e)
