### ISSUE TITLE
shortcut idea: being able to open a vst fx window of choice with a shortcut

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#374]
lets say, i have this frequency analyser vst that is on my master channel, could i have a shortcut that opens this analyser? wherever i am located in renoise.

to assign shortcuts: maybe open a box which shows all vst fx that are currently used in the project - then ability to assign per unique vst (if thats possible?)

**Comment by esaruoho** [comment]
<img width="470" alt="Screenshot 2024-09-06 at 9 43 32" src="https://github.com/user-attachments/assets/f8b423f4-8591-4797-936e-3e248cba1807">

the "all vst fx currently used in the project" -> i opted for a solution that shows all the devices available, and you can pick the ones you want. it'll autodetect where it is in master or selected track, and open it.

please check out a build, and close ticket if works.

**Comment by dmt-hub** [comment]
Perfection! thanks again for your hard work! 🙏
