### ISSUE TITLE
Display and focus the pattern matrix

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#390]
When I want to display the pattern matrix, that is usually also when I want to focus on it.
I want to focus as the default behavior.

https://github.com/user-attachments/assets/3c577757-0e91-49b1-8c80-71c9c7a0e596

**Comment by tkna91** [comment]
https://forum.renoise.com/t/the-api-wishlist-thread/29285/381

**Comment by esaruoho** [comment]
closing as blockedbyapi - will revisit when api updates.
