### ISSUE TITLE
vst / devices / vsti dialog add-on - randomize amount slider

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#403]
![21696](https://github.com/user-attachments/assets/f60ba981-85bb-42e7-9e75-07f460dba225)

![25483](https://github.com/user-attachments/assets/65a5851b-65b2-4fee-9978-c5c23becb419)

now it selects too many devices when choosing randomize
with such slider one could set the slider only 10% for getting only a couple of devices

**Comment by esaruoho** [comment]
![renoise loader dialog](https://github.com/user-attachments/assets/88cfd3ed-5068-42b9-a6d2-1aa392ab40ff)
