### ISSUE TITLE
vst/au dialog too big for screen

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#404]
![afbeelding](https://github.com/user-attachments/assets/5905d28f-d4ea-4655-b0b8-32eb5bf1198b)

 "no audiounits, show vst3: 40"

**Comment by esaruoho** [comment]
![renoise loader dialog](https://github.com/user-attachments/assets/9e0e88aa-2eee-4f47-bd3a-f215be90e932)
