### ISSUE TITLE
 request: copy waveform selection to new sample slot, mute original sample slot

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#457]
copy waveform selection to new sample slot, mute original sample slot

**Comment by esaruoho** [comment]
<img width="951" alt="Screenshot 2024-08-27 at 22 37 32" src="https://github.com/user-attachments/assets/4f510ae1-5ec4-454c-9452-44b76a2d1800">

**Comment by dmt-hub** [comment]
Thank you!
