### ISSUE TITLE
request: random sampleslot transposer

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#458]
randomly transpose the selected sampleslot -6st / +6st + finetune

**Comment by esaruoho** [comment]
@dmt-hub need more info. +6-6 transpose yes, but what about finetune, how much?
and is this done for all samples in the instrument, or only the selected one?

**Comment by dmt-hub** [comment]
@esaruoho  a random transpose (between -6 -> +6) + random finetune - on the selected sampleslot.

**Comment by esaruoho** [comment]
![randomize +6-6 pitch +127-127 finetune](https://github.com/user-attachments/assets/c512160f-d9f4-4b10-9aae-6df744b571a6)
