### ISSUE TITLE
Request: Octamed Pickput: save/load pickput entries into textfile

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#461]
add a save and load button to save all pickput entries into a easy readable text file.

**Comment by esaruoho** [comment]
<img width="963" alt="Screenshot 2024-10-02 at 13 10 00" src="https://github.com/user-attachments/assets/7efc6835-89f4-4ec9-8c8b-eea673719818">
