### ISSUE TITLE
Request: Octamed Pickput: Randomly place puts in a track

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#462]
Randomize button (with fill probability slider) - which randomly places puts into the active track

**Comment by dmt-hub** [comment]
<img width="996" alt="Screenshot 2024-08-25 at 21 22 15" src="https://github.com/user-attachments/assets/e4257332-12bb-4c3e-9af7-240e05c562e4">

**Comment by dmt-hub** [comment]
also for randomizing: randomize w/ editstep

**Comment by esaruoho** [comment]
<img width="947" alt="Screenshot 2024-10-02 at 13 10 55" src="https://github.com/user-attachments/assets/1d99956b-c7f9-4202-842a-f289966d7d6c">

Randomize + slider added.
