### ISSUE TITLE
Trim Silence Beneath Threshold

### ISSUE THREAD

**Issue by ghost** [esaruoho/org.lackluster.Paketti.xrnx#48]
Is it possible to add a keybind in the sample editor that can delete silence beneath a db threshold. There was a tool that did this but it is no longer compatible with 3.4

Perhaps a preference setting beforehand and a keybind that can immediately activate the process.

The beginning and end of samples are where it's most important in my opinion especially when using bxx commands on samples that have huge amounts of silence after the waveform. This would be a godsend

**Comment by esaruoho** [comment]
@icasiino do you have a link to the tool somewhere, please? before i go look for it and find n+1 tools (none of which are the one you are referencing) :)

when you say Bxx commands, do you mean `0B00` & `0B01`. ? 
then you might really like these shortcuts:
<img width="318" alt="Screenshot 2024-05-01 at 13 11 27" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/f06cf90a-6947-4d48-aaff-0e66ccb6667a">

**Comment by icasiino** [comment]
Yes that's exactly the tool I was referring to I also linked to it in the forum as well.

As far as the bxx command yes I meant 0bxx for backwards and forward. The shortcuts are great however the trim silence is needed because if one uses the 0b00 command and the sample has a lot of silence at the end,u won't hear anything while sequencing because the sampler is now playing the sample from the end where there is no sound

**Comment by esaruoho** [comment]
apparently there's some version of this available for 2.7 at https://www.renoise.com/tools/add-remove-silence
but they haven't made a Renoise3 version of it. let's see if it can work.

**Comment by icasiino** [comment]
This is the version I tried myself. Is doesn't auto update so and I don't think the source is available

**Comment by icasiino** [comment]
I wqs just informed that the ModFX render tool does this already.

https://forum.renoise.com/t/new-tool-3-4-3-modfxrender-v2-0-build-037-november-2023/60043

I wouldn't mind it being in paketti without the need for a gui to activate the process though.

**Comment by esaruoho** [comment]
> I was just informed that the ModFX render tool does this already.
> https://forum.renoise.com/t/new-tool-3-4-3-modfxrender-v2-0-build-037-november-2023/60043
> I wouldn't mind it being in paketti without the need for a gui to activate the process though.

i really hope it will be easier to take the abandoned 2.7 tool code and modify that to work, rather than take this dude ulneiz's code (he sells some of his stuff so i'm not sure how much he's willing to just "give away").
but i'll see about this stuff.

**Comment by icasiino** [comment]
Excellent, and if he asks a price just let me know 😉

**Comment by esaruoho** [comment]
here's "absolute silence"

![strip sielnce](https://github.com/user-attachments/assets/8e8a709f-987f-4b95-997b-3d8e66f611e5)

but it seems like the threshold needs to be there.

**Comment by esaruoho** [comment]
<img width="605" alt="Screenshot 2024-08-08 at 9 37 30" src="https://github.com/user-attachments/assets/62f03222-b39a-46d1-bf8c-8b4ed55463ee">
<img width="398" alt="Screenshot 2024-08-08 at 12 03 41" src="https://github.com/user-attachments/assets/64f0529e-014a-4220-aea2-644b3bc8db5e">
