### ISSUE TITLE
Enable/Disable Velocity Tracking (per sample, and per instrument)

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#50]
@icasiino 
Next, the Sampler Velocity Tracking - 
It seems it is possible to set the Min / Max (0...127) Velocity Tracking - and something about Clamp and Scale (Different Modes)

and also something like `Mappings velocity->volume and key->pitch options.`  and `Velocity range the mapping is triggered for.`  - are we specifically talking about setting Velocity Range 127...127 so no matter what, it will hit at full volume, (Disabled Velocity Tracking? would that work?) and then 0...127 for "Enabled Velocity Tracking", for either SelectedSample, or SelectedInstrument(=ALL)? 

I'm wondering about the usecase of this, could you provide a XRNI example for me as a zip, you can email it to esaruoho@icloud.com if that helps (if you want to keep it private). 

_Originally posted by @esaruoho in https://github.com/esaruoho/org.lackluster.Paketti.xrnx/issues/30#issuecomment-2068180257_

**Comment by icasiino** [comment]
Disabling the velocity tracking is what I mean(turning it off completely) and toggling back to having it enabled (0-127) 

Most ideal usage would be for chopped/sliced melodies

**Comment by esaruoho** [comment]
@icasiino i just used a script command to turn this off.
if this is off, is this "Disable Velocity Tracking"?

<img width="1119" alt="Screenshot 2024-05-04 at 16 19 07" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/311aa25c-bcdb-4e62-91ae-49688e31e97d">

if so, i'll continue onwards and, i guess, successfully make it happen.

**Comment by icasiino** [comment]
Yes sir 🫡 That's it. Awesome bro

**Comment by esaruoho** [comment]
closing as duplicate of #43 
i'll send you a DM on renoiseforum when this lands. now working on other features.
<img width="350" alt="Screenshot 2024-05-04 at 17 05 06" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/c0174d80-ec4d-4f19-bd97-9becec829945">
<img width="353" alt="Screenshot 2024-05-04 at 17 05 14" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/b65117a2-b444-48bd-8e38-b5dfb5801be3">
