### ISSUE TITLE
`LPB*2` & `LPB/2`

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#500]
I noticed that there are no shortcut key just to do the following
- Double the LPB
- Reduce LPB by half

Please consider implementing this.

![20240831-042901_screenshot](https://github.com/user-attachments/assets/9b9d91bd-6781-4132-b6d4-91177f437301)

**Comment by esaruoho** [comment]
"the function to halve LPB does not change the value when LPB is odd. Ignore."
do nothing if trying to double over 32
because if you double 40 to 64, you'd have a hard time getting it back to 40 or 20.

**Comment by tkna91** [comment]
Oh, sorry, the maximum value of LPB is 256. The above analogy is incorrect.
- If you multiply 40 by 2, you get 80 (less than 256), so this is valid.
- If you multiply 160 by 2, it would be 320, so it would be over 256. In that case, there is no need to make it 256, etc., so ignore it.

**Comment by esaruoho** [comment]
<img width="348" alt="Screenshot 2024-08-31 at 16 21 10" src="https://github.com/user-attachments/assets/6e62be83-147e-4f74-9793-f7e00b24c3f9">
