### ISSUE TITLE
DC Filter/Soft Clipping/Auto Gain for Master

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#502]
These shortcut keys do not seem to be a standard feature.
- DC Filter
- Soft Clipping
- Auto Gain

Since they are always unset when playing `*.xm`, `*.mod`, `*.it` it would be useful to be able to set them with shortcut keys.

https://github.com/user-attachments/assets/2f9e7872-e655-49a3-bc99-bec805421228

**Comment by esaruoho** [comment]
@tkna91 this is blocked by API - please request for all 3 to be made available by Renoise API :)

**Comment by esaruoho** [comment]
i'll close this ticket until there's an api update. when there's an api update, i'll revisit all `blockedbyAPI` tickets :)
