### ISSUE TITLE
Song Options

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#503]
Surprisingly, this also does not seem to be a standard feature.
It would be useful if it were.

![image](https://github.com/user-attachments/assets/d55b5554-000a-4182-9a5d-3577aeeb3470)

**Comment by esaruoho** [comment]
@tkna91 please request this in the api functions thread, this is not available.

**Comment by tkna91** [comment]
i did it https://forum.renoise.com/t/the-api-wishlist-thread/29285/382
