### ISSUE TITLE
Pattern Editor->Navigation->jump to Sends

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#504]
There does not seem to be a `jump to Sends` in the pattern editor by default.
It would be useful to have it.

https://github.com/user-attachments/assets/cbf3fd57-1be1-4db6-9ea9-d01d3e006eeb

**Comment by esaruoho** [comment]
<img width="346" alt="Screenshot 2024-09-01 at 21 41 06" src="https://github.com/user-attachments/assets/05dbf2d8-22ac-4dce-85dc-ae02edb9ff46">
