### ISSUE TITLE
what if pitchbend instrument loader was automatable?

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#52]
@tkna91 wdyt?
currently there's no way to draw a pitchbend automation curve. would you like that?
reason im asking is i could easily do it based on some new details.

**Comment by esaruoho** [comment]
give it a go, @tkna91

[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15204904/org.lackluster.Paketti_V3.54.xrnx.zip)

**Comment by tkna91** [comment]
Yes, that's convenient. Thanks.

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/51ee9b20-1b87-4def-9866-36506dca953b


I seem to get an error when starting Renoise again.
![20240504-112248_screenshot](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/13908a9d-9eb0-498d-b9fc-1b4a116e9a65)

**Comment by esaruoho** [comment]
ok, that's easy to fix.
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15208224/org.lackluster.Paketti_V3.54.xrnx.zip)

sorry, i was working on some other request which has turned out to be very very complex to do.
and that was not properly initialized.

also, please have a look at this:
https://www.loom.com/share/d961bb21413a43a6942a5dac03bab964?sid=a3a0c4d7-0954-47fe-9fb3-50637decda92

**Comment by tkna91** [comment]
Yes, I checked. It looks good. Thanks!

**Comment by esaruoho** [comment]
ok, closing ticket. nice! :)

**Comment by esaruoho** [comment]
reopened, since the 
<img width="729" alt="Screenshot 2024-05-04 at 10 43 38" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/8ec1f920-06ec-4727-a9f5-808ba292b2e8">

was not yet added. i'll add it and then it'll be ready to go.

**Comment by esaruoho** [comment]
also i need to disable Autoseek, for automation of pitchbend to be possible. i'l need to tweak this more.

so

1. add `*Instr. Macros` to track dsp
2. disable Autoseek

then it'll work as expected.

**Comment by esaruoho** [comment]
ok. some updates.

- [X] Disable Autoseek
- [X] Load `*Instr. Macros`
- [X] Minimize `*Instr. Macros` 
- [ ] Name `*Instr. Macros` with a name
- [X] Display Automation
- [ ] select PitchBend from Automation

Once I get the select PitchBend from Automation, I'll want to ship a new version for you.
..
looks like unfortunately the PitchBend (or even device) selection within the API is blocked.

I've left a request for it, but since i'm the only one posting, they won't let me post new posts :(

**Comment by esaruoho** [comment]
@tkna91 ok here's a build that shows automation and already has instr*macros
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15209917/org.lackluster.Paketti_V3.54.xrnx.zip)

do let me know if it works for you too. closing this ticket - and please open tickets if there are bugs
