### ISSUE TITLE
BPM Increase(+0.5)/Decrease(-0.5)

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#520]
When changing the BPM with the keyboard, the following is too slow or too fast for my environment.

- BPM Increase(+0.1)/Decrease(-0.1)
- BPM Increase(+1)/Decrease(-1)

https://github.com/user-attachments/assets/4180aba6-7c8d-4475-b131-c3699d539684

I would be happy to have the following, which are in between.

- BPM Increase(+0.5)
- BPM Decrease(-0.5)

**Comment by esaruoho** [comment]
<img width="362" alt="Screenshot 2024-09-03 at 20 49 43" src="https://github.com/user-attachments/assets/9203f8bf-742a-40ef-be5c-a7b7de21bc97">
