### ISSUE TITLE
Pitch-Operand is not `+` but `*`

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#534]
It seems that Pitch-Operand is not set to `+` and is set to `*`.

https://github.com/user-attachments/assets/bdd91ffe-1d3f-41d9-b831-db065685aead

This is the key to TR909-like automation with pitch in this way, so it would be nice if it could be set to `+`, the same as the default.

https://github.com/user-attachments/assets/691ed891-4780-48c6-af54-a2f6ef0538f3

**Comment by esaruoho** [comment]
i forced all modulation devices to load as `+` instead of `*`
