### ISSUE TITLE
Set to multiple/stereo outputs routing

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#542]
EDIT: I rethought it to be a simple form.

- Set to multiple outputs routing
- Set to stereo outputs routing
- Toggle multiple/stereo outputs routing

https://github.com/user-attachments/assets/bd170663-450e-4539-9fb2-638c79ff2141

The following is an example when there are 4 stereo outputs that can be assigned.

# Set to multiple outputs routing

1. Assigns the currently routable outputs in order, starting with track 1.
1. When the number of outputs to be assigned has been exhausted, assign the last output.

https://github.com/user-attachments/assets/a41e0509-a7ef-4bef-ae2d-08df6dff8970

| Track | Output |
| --- | --- |
| 1 | Output 01 Left/Right |
| 2 | Output 02 Left/Right |
| 3 | Output 03 Left/Right |
| 4 | Output 04 Left/Right |
| 5 | Output 04 Left/Right |
| 6 (Mst) | Output 04 Left/Right |
| 7 (S01) | Output 04 Left/Right |

| Track | Output |
| --- | --- |
| 1 | Output 01 Left/Right |
| 2 (Mst) | Output 02 Left/Right |
| 3 (S01) | Output 03 Left/Right |

# Set to stereo outputs routing

1. Assign the output routing of all current tracks to Master.
1. Set the Master output to `Output01`.

https://github.com/user-attachments/assets/305a8403-81d5-4072-afd6-012db4c901a0

| Track | Output |
| --- | --- |
| 1 | Master |
| 2 | Master |
| 3 | Master |
| 4 | Master |
| 5 | Master |
| 6 (Mst) | Output 01 Left/Right |
| 7 (S01) | Master |

# Toggle multiple/stereo outputs routing

Toggle the above.

**Comment by tkna91** [comment]
In the toggle process, it seems to me that the following process should be used.
- Multitrack if each track is not a condition for multitrack output
- Stereo track if each track meets the requirements for multi-track output

**Comment by tkna91** [comment]
Suggestions from the conversation

# Set to multiple outputs routing

1. Assigns the last output to the master track.
1. Assigns the currently routable outputs in order, starting with track 1.
1. When the number of outputs to be assigned has been exhausted, assign the master.

| Track | Output |
| --- | --- |
| 1 | Output 01 Left/Right |
| 2 | Output 02 Left/Right |
| 3 | Output 03 Left/Right |
| 4 | Master |
| 5 | Master |
| 6 (Mst) | Output 04 Left/Right |
| 7 (S01) | Master |


https://github.com/user-attachments/assets/08e19f7e-90ef-44cd-8258-3e6a72359841


| Track | Output |
| --- | --- |
| 1 | Output 01 Left/Right |
| 2 (Mst) | Output 02 Left/Right |
| 3 (S01) | Output 04 Left/Right |

https://github.com/user-attachments/assets/4f32de98-bb73-44f1-b698-cb4cbc5e1d6e

**Comment by tkna91** [comment]
I'm starting to think the idea I wrote in the OP (blind serial assignment) is the way to go.
How the routing is done on the Send device is on a case by case basis, and the number of tracks needed is also on a case by case basis.
At least as long as it looks like it, you can ARM consecutive tracks on the recording side of the DAW.
You can check and sort out which one was the master and which one was the send after recording.
ARMing 64 tracks when you are only recording 3 tracks is tedious and complicated. Considering that we will be working during a live show, etc., it would be better to keep it simple because it would cause panic.
The purpose is simple multi-track capture.

**Comment by esaruoho** [comment]
this now serially dumb-organizes all tracks and all sends to be from first output to last output and loop when the last output is started, i.e. start from beginning.

<img width="458" alt="Screenshot 2024-09-30 at 17 26 02" src="https://github.com/user-attachments/assets/ea11add0-02fa-46c3-a948-f3911ed21655">
<img width="1146" alt="Screenshot 2024-09-30 at 17 25 36" src="https://github.com/user-attachments/assets/1ff59d9e-d01d-4c8d-a2aa-46362bd13029">

![image](https://github.com/user-attachments/assets/6db0d433-6c21-42ac-ac1b-aab7c40982eb)
<img width="795" alt="Screenshot 2024-09-30 at 17 27 51" src="https://github.com/user-attachments/assets/5cf41ff0-871b-4be2-b2ce-9403ad118af9">

**Comment by esaruoho** [comment]
![noncontinual-continual](https://github.com/user-attachments/assets/fa6ab032-a526-4a44-b2d8-16a6deceae45)

**Comment by tkna91** [comment]
Confirmed. This looks perfect.

https://github.com/user-attachments/assets/ec3348aa-bc72-4225-9b3f-ba0e30b1b606
