### ISSUE TITLE
128 MIDI knobs for manipulating the selected device

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#543]
MIDI Map to control the parameters of the selected device
- [x] MIDI Map: Manipulate parameters
- [x] Operations during rec are written to automation

https://github.com/user-attachments/assets/5353ce5d-17b8-4254-8f5f-431a27dfeaf8

**Comment by esaruoho** [comment]
![image](https://github.com/user-attachments/assets/17a6bbe2-84ac-46e8-b0c3-fa31f33e01c8)
![image](https://github.com/user-attachments/assets/1aa88e33-2486-4029-91f7-91954f53d428)

**Comment by esaruoho** [comment]
i think it's safer it is "follow pattern, editmode = on, playing = on"

**Comment by tkna91** [comment]
Are you saying that you don't record automation except during REC?

**Comment by tkna91** [comment]
I can't seem to move the slider with the MIDI knob when it is play only with no follow.

https://github.com/user-attachments/assets/42379b2a-5502-461b-a524-5d6056a7d5e0

**Comment by tkna91** [comment]
The above appears to have been corrected.
It looks like the automation is written in the playback head on the rec when I'm not following.

https://github.com/user-attachments/assets/da6ff18a-c794-4cb3-b4b8-2a2ecd07166c

**Comment by esaruoho** [comment]
> Are you saying that you don't record automation except during REC?

automation is recorded only in record mode.

**Comment by tkna91** [comment]
> tkna — 今日 19:31
> However, it seems to be writing on the playback head instead of the current line during edit mode. I have not follow and that behavior seems odd.
> esaruoho — 今日 19:31
> playback head..hmm.
> ok.. let's start with a simple thing. a midimapping for pattern line
> so then i can see, okay, i'm on pattern row 30, i change automation, does it change at playhead or at row30

I think it makes sense to change only the row 30 parameters.
I feel the current behavior is problematic because it is rewriting the automation on the playback head.

**Comment by tkna91** [comment]
Currently, it is written to the playback head when the edit mode is on.

https://github.com/user-attachments/assets/c5f69359-1aca-4e75-a979-f10f6905a1be

**Comment by tkna91** [comment]
# Tested
- [x] editmode is on, playing is off -> write to where cursor is in automation
- [x] editmode is off, playing is off / on -> parameter change to device.
- [x] editmode is on, playing is on -> write to where cursor is in automation
- [x] editmode is on, playing is on, follow pattern is on -> write to where playhead is in automation.
- [x] if playback is OFF, editmode is ON and follow pattern is ON -> then still type to where cursor is.
- [x] playing, editmode on, no follow pattern -> type to selected row INSTEAD of playhead "as if follow pattern was ON"
- [x] not playing, editmode on, follow pattern on -> type to selected row  INSTEAD of playhead position

Defects found #546
