### ISSUE TITLE
[Load Plugins Dialog] After adding a plugin, activate the Plugin window, not the Sampler window

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#551]
https://github.com/user-attachments/assets/ea8b8695-a6f4-4978-b4e0-b9921b388220

**Comment by esaruoho** [comment]
what an interesting bug. this only happens if i'm in instrument pages. if i'm o pattern editor, nothing happens.

**Comment by esaruoho** [comment]
i'll definitely fix this soon. sorry!

**Comment by esaruoho** [comment]
fixed
