### ISSUE TITLE
Change Selected Track Volume

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#553]
The standard keybindings include the following, but they can only be used in the Mixer window.

- Decrease Volume
- Increase Volume

https://github.com/user-attachments/assets/94572d08-1a83-4571-9ddb-abc9c0a970af

It would be useful to have the following keybindings that can be used in any window to adjust the volume of the selected track.

- Change Selected Track Volume by +0.01
- Change Selected Track Volume by +0.05
- Change Selected Track Volume by +0.1
- Change Selected Track Volume by -0.01
- Change Selected Track Volume by -0.05
- Change Selected Track Volume by -0.1

**Comment by esaruoho** [comment]
<img width="353" alt="Screenshot 2024-09-14 at 11 23 19" src="https://github.com/user-attachments/assets/6e691862-bf50-4fb3-bf57-c79af5629892">
