### ISSUE TITLE
Change Selected Track Volume (dB)

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#554]
This replaces the units handled in the #553 implementation with `dB`.
---
The standard keybindings include the following, but they can only be used in the Mixer window.

- Decrease Volume
- Increase Volume

https://github.com/user-attachments/assets/94572d08-1a83-4571-9ddb-abc9c0a970af

It would be useful to have the following keybindings that can be used in any window to adjust the volume of the selected track.

- Change Selected Track Volume by +0.01 db
- Change Selected Track Volume by +0.05 db
- Change Selected Track Volume by +0.1 db
- Change Selected Track Volume by -0.01 db
- Change Selected Track Volume by -0.05 db
- Change Selected Track Volume by -0.1 db

**Comment by esaruoho** [comment]
<img width="351" alt="Screenshot 2024-10-09 at 10 13 36" src="https://github.com/user-attachments/assets/88020494-39e7-4339-a4bd-33249529e683">
