### ISSUE TITLE
Loop set: Percussion/Texture

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#560]
It would be useful to be able to use key bindings to perform the following two types of processing that are often performed to set up loop samples.

**Loop set: Percussion**
- Beatsync: ON
- Mode: Percussion
- Loop: Forward
- Playback: Autoseek

**Loop set: Texture**
- Beatsync: ON
- Mode: Texture
- Loop: Forward
- Playback: Autoseek

https://github.com/user-attachments/assets/c8346a4d-583b-401b-be69-36eafea0e951

**Comment by esaruoho** [comment]
that's easy

**Comment by esaruoho** [comment]
<img width="351" alt="Screenshot 2024-09-17 at 22 28 17" src="https://github.com/user-attachments/assets/3606994d-8b47-4baf-a590-53411b7a89b6">
