### ISSUE TITLE
Read BeatSync Lines from Selection In Pattern

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#561]
the description in Sampler says
```
Beatsync: When enabled, the length of sample playback will be automatically changed 
so that it lasts for the selected amount of pattern lines, and this will auto-update to
match any changes to the BPM or LPB. This is especially useful for syncing drumbeat
loops. As an alternative, you can leave the checkbox disabled and instead press the
3.0 sampler-beatsyncT.png button, which will set the Transpose and Finetune values
to match the current tempo. Our video tutorial goes into more detail.
```
https://tutorials.renoise.com/wiki/Sampler

If you read this "the wrong way" - you think: "Selected Amount of Pattern Lines == BeatSync Lines".
this is of course not how the manual supposedly tries to explain it, but this is how i think it should work.

**Comment by tkna91** [comment]
I think `selected amount of pattern lines` is the value set in the Beatsync text box.
![image](https://github.com/user-attachments/assets/1f3bf42e-10dc-435e-8c30-24e16a7284bf)

**Comment by tkna91** [comment]
However, this would complicate operations because the user would have to calculate and manually set the selection manually to play back the sample length.

**Comment by tkna91** [comment]
Of course, it might be interesting to have that feature on its own.
I have yet to see the need for it, but perhaps we can add it to the flavor of the #560 feature set and then think about its necessity.

**Comment by esaruoho** [comment]
<img width="346" alt="Screenshot 2024-09-18 at 0 01 48" src="https://github.com/user-attachments/assets/2ccb623f-4caf-41dc-8a2a-53f33628dee6">
