### ISSUE TITLE
Repeat multi-line, multi-track selections to the end of the pattern

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#563]
- Repeat columns of selection until end of pattern
- If there is no selection, repeat the current cursor contents.
- Repeat for multiple track selections.
- Repeat for multiple line selections

https://github.com/user-attachments/assets/283f981a-ca8f-4212-9311-2ec76f62f1df

_Originally posted by @tkna91 in https://github.com/esaruoho/org.lackluster.Paketti.xrnx/issues/562#issuecomment-2356438621_

**Comment by esaruoho** [comment]
please confirm for me whether "Replicate at Cursor" already does this.
there's a selected track flavor, and an all tracks flavor.

**Comment by tkna91** [comment]
My apologies. `Replicate All Above + Current` seems to be it.
# This is useful. Thanks!

https://github.com/user-attachments/assets/5dcc7afc-adaa-44b3-81c0-056ded73c400

**Comment by tkna91** [comment]
Sorry, but I found that `Replicate All Above + Current` is not what I expected, as it does the process on all columns, not the selected columns.
I would like a key binding that repeats the selected range to the end of the pattern in the selected columns or selected tracks.

> - Repeat columns of selection until end of pattern
> - If there is no selection, repeat the current cursor contents.
> - Repeat for multiple track selections.
> - Repeat for multiple line selections

https://github.com/user-attachments/assets/1e1901f5-f4b0-4a36-a565-216414691395

**Comment by tkna91** [comment]
This `Flood Fill with Selection` appears to be working as expected!

https://github.com/user-attachments/assets/c87cb730-3c84-4301-bffb-09e38ae1cec2
