### ISSUE TITLE
Added `Mute Group: Group1` to the processing list of `Loop set: Percussion/Texture`

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#564]
I found that if multiple Note columns are used, the playback content will be duplicated if left as is.

https://github.com/user-attachments/assets/423b77ca-5c5d-4b06-a7ad-27b6420e9b1e

Since loop samples are usually not duplicated, it is useful to add a `Mute Group`, as shown below.

**Loop set: Percussion**
- Beatsync: ON
- Mode: Percussion
- Loop: Forward
- **Mute Group: Group1**
- Playback: Autoseek

**Loop set: Texture**
- Beatsync: ON
- Mode: Texture
- Loop: Forward
- **Mute Group: Group1**
- Playback: Autoseek

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/issues/560

**Comment by tkna91** [comment]
The reason this is better is that I may want to control the probability of the scale used.

https://github.com/user-attachments/assets/6e77feed-425f-4e62-b523-59882f4ef9dc

**Comment by esaruoho** [comment]
mute group added to both.
