### ISSUE TITLE
Halve/Double BPM

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#580]
- Halve BPM
- Double BPM
- Halve of Halve BPM
- Double of Double BPM

https://github.com/user-attachments/assets/c9831f0c-8283-413f-8786-e74563d8e51e

**Comment by esaruoho** [comment]
So 120 becomes 30bpm
And 60 becomes 240bpm?

**Comment by tkna91** [comment]
Yes.

**Comment by esaruoho** [comment]
![double double bpm halve halve bpm](https://github.com/user-attachments/assets/dc07cbaf-f751-41e4-ab32-8abd55fff2e8)
