### ISSUE TITLE
Halve of Halve/Double of Double LPB

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#581]
- Halve of Halve LPB
- Double of Double LPB

https://github.com/user-attachments/assets/a647c034-e5a3-4b67-9845-04a755259506

**Comment by esaruoho** [comment]
So.. lpb 8 becomes 2?
And lpb 4 becomes 16?

**Comment by tkna91** [comment]
Yes. I found that `Halve of Halve`, `Double of Double` is often in the range of practical and effective rhythms, so I thought it would be useful to have this.

**Comment by esaruoho** [comment]
![double double lpb halve halve lpb](https://github.com/user-attachments/assets/330accf3-9f6f-4a64-b961-e085b8730cd0)
