### ISSUE TITLE
Halve of Halve/Double of Double Beatsync Line (Selected Sample)

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#582]
- Halve of Halve Beatsync Line (Selected Sample)
- Double of Double Beatsync Line (Selected Sample)

https://github.com/user-attachments/assets/abfda9b7-c886-4bcd-8d21-76e52f427910

**Comment by esaruoho** [comment]
<img width="357" alt="Screenshot 2024-09-22 at 21 48 00" src="https://github.com/user-attachments/assets/daa177fb-763a-472e-9322-5edf6e7c08ad">
<img width="341" alt="Screenshot 2024-09-22 at 21 48 05" src="https://github.com/user-attachments/assets/a817ae1f-4db3-4b1b-af89-d360d2b002f6">
