### ISSUE TITLE
Enable/Disable the Nth device of the selected track

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#583]
It would be useful to be able to Enable/Disable the Nth device of the selected track.
This makes it easier to play, for example, to enable multiple effects at the same time.

- Enable the 001th device of the selected track
- Disable the 001th device of the selected track
- Toggle(Enable/Disable) the 001th device of the selected track

I think 128 is sufficient for the number of targets.
It would be better if it could be recorded in Automation during Edit Mode.

https://github.com/user-attachments/assets/38286a84-65b9-477a-bc02-a733555c7150

**Comment by esaruoho** [comment]
So these would be midimappings and Shortcuts, right?

**Comment by tkna91** [comment]
Yes, it is. I think it will make live performance and composition about effects easier and more effective.

**Comment by tkna91** [comment]
I believe that it is preferable to have three types of Enable/Disable/Toggle to ensure reliable operation.
For example, we can respond to the need to ensure that devices 001-009 are Enable, but devices 010-128 are Disable.
We also envision that these can be operated not only manually, but also by scripts.
MIDI and keyboard inputs are relatively simple and easily scriptable.

**Comment by tkna91** [comment]
The number might be 34 for now instead of 128. Currently, the automation command can only record up to 34 devices, and the “Active/Bypassed” envelope does not seem to allow right-click recording.

https://forum.renoise.com/t/recorded-by-right-clicking-on-the-active-bypass-envelope-of-the-track-device/73304

https://github.com/user-attachments/assets/cce43ffa-8a7a-48a0-9b31-2b6cef43190b

**Comment by tkna91** [comment]
Also, naively, assigning 128 key bindings may be quite reckless, considering that at least 2-3 layers of modify keys would be needed.
Given that, 34 seems like a good number.
