### ISSUE TITLE
Hand crank music box playback

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#599]
It would be interesting to have the following key bindings and MIDI Map to enable semi-manual playback like a hand-cranked music box.

**Play Current Line (2nd)**
1. Play Current Line
1. Go to Next Line

**Play Previous Line**
1. Go to Previous Line
1. Play Current Line

This is intended for use, for example
- Assigning the mouse wheel to output any key bindings by input device remapping software
- Operate with a MIDI knob on a rotary encoder

https://github.com/user-attachments/assets/51a84b14-c776-4fa4-be49-c2ef5e8d24f2

**Comment by tkna91** [comment]
i requested https://forum.renoise.com/t/the-api-wishlist-thread/29285/388

**Comment by esaruoho** [comment]
<img width="373" alt="Screenshot 2024-10-01 at 13 54 01" src="https://github.com/user-attachments/assets/55e2bad4-4386-40bd-b9e0-c89e7a653293">
