### ISSUE TITLE
Jump to a random line in the pattern

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#602]
1. Play the current line
2. Jump to a random line in the pattern

https://github.com/user-attachments/assets/34f32ce6-c195-4ec8-957e-9aa6c5e8c985

**Comment by esaruoho** [comment]
<img width="375" alt="Screenshot 2024-10-01 at 14 47 32" src="https://github.com/user-attachments/assets/ed0e5fea-67eb-4036-b313-d3307765d187">

**Comment by tkna91** [comment]
It would be nice to have some flavors that don't stop regenerating.

https://github.com/user-attachments/assets/efe8ebb6-87f2-4f5d-8d9e-05b3bc23660a
