### ISSUE TITLE
Playback of specified lines 0-511

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#603]
The idea is to create a key binding and MIDI mapping to play each of the 0x000(0)-0x1FF(511) lines of the pattern.
8x8=64, 64*8=512, so for an 8x8 MIDI pad, 8 layers would be enough to cover it.
We could also use key bindings to pick up and play back some parts of the keyboard.

https://github.com/user-attachments/assets/beec8806-3e71-48b4-9d85-44e28e0944f6

**Comment by tkna91** [comment]
If the task of generating code or files using sequential numbers seems tedious to you, please let me know.
I am very good at doing such tasks quickly using bash or vim.

**Comment by tkna91** [comment]
> esaruoho — 今日 04:55
> ok let's see
> playback of specified rows
> so this is.. 512 shortcuts for playing a specific row?
> tkna — 今日 05:00
> Yes, I would like to have 512 units. In my current usage, I only need about 16, but having 512 would increase the number of use cases I can handle.
> For example, I may want to point to a specific place in a pattern with a high tempo or LBP value.
> The use is to play any 8 points between 1-511.
> In fact, this function is a kind of keyboard.
> In this sense, each line can be used to assign to a MIDI keyboard.
> So each line becomes a sound source to be played.
> It would be close to the image of the MPC-like performance method.
> tkna — 今日 05:12
> This function alone has the potential to create a variety of musical genres yet to be discovered.
> The functionality is simple and straightforward, and the method of performance is straightforward. However, the music that users will create with it should be quite diverse.

**Comment by esaruoho** [comment]
![Uploading Screenshot 2024-10-02 at 9.42.45.png…]()

**Comment by esaruoho** [comment]
<img width="770" alt="Screenshot 2024-10-02 at 9 42 45" src="https://github.com/user-attachments/assets/462e21aa-be66-43a7-b769-870cf8a9ee0c">
