### ISSUE TITLE
Enhancements to `Paketti Macro 01`

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#605]
#379 

Some considerations need to be made, but I will write them as they are.

- Add editor and mixer views as switching targets
- Provide 8 differently numbered versions of the same function.
- It would be nice to be able to specify the order of focus in some way. First the phrase, then the key zone, etc.
- `Paketti Macro 01` is a confusing name for a function, maybe something like `Focus/View Cycle Preset 01` would be better.

**Comment by esaruoho** [comment]
edtor and mixer views are switching targets.
8 slots provided.
i don't know what "order of focus" means. API provides no focus. but you can select the slot cycles so that one starts from phrase editor, and another to keyzone.

**Comment by tkna91** [comment]
> but you can select the slot cycles so that one starts from phrase editor, and another to keyzone.

Yes, that is what I meant. Slot cycles is a more accurate way to describe it.

**Comment by esaruoho** [comment]
<img width="166" alt="Screenshot 2024-10-06 at 14 03 26" src="https://github.com/user-attachments/assets/7dbd0a09-2095-4e1f-b913-54a20209a0a6">

@tkna91 i believe this should set your mind at ease.

**Comment by esaruoho** [comment]
these have all been addressed
