### ISSUE TITLE
Improvement of `Play at Row 001-512`

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#606]
#603
- Make the line numbers in the function name `0x000`-`0x1FF` instead of `001-512`.
- Allow playing even when stopped, similar to `Play Current Line`
  - The reason this is important is that it is intended to be able to play as if you were calling up a sample on the keyboard, regardless of the Renoise sequence.
  - Of course, it would be nice to be able to play during a sequence as well as `Play Current Line`.

https://github.com/user-attachments/assets/8f59bac9-c3ec-457f-9cb4-154617f4876a

**Comment by esaruoho** [comment]
done
