### ISSUE TITLE
[Wipe & Slices Settings] Add “Off” to `Slice BeatSync Mode`

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#611]
If the main use is to create drum sets by slicing drum phrases, it would be useful to be able to turn off Beatsync during Slice&Wipe.

![image](https://github.com/user-attachments/assets/d806b395-9ea3-48fe-b6f4-4d349b8db150)

**Comment by esaruoho** [comment]
@tkna91 there's a quirk here that you might not be aware of.
if you have beatsync mode OFF in the original sample, then wipe&slice will not introduce beatsync to the slices. they will play straight.
but if beatsyncline is on, then the wipe&slice samples will have beatsyncline sets.
<img width="155" alt="Screenshot 2024-10-03 at 23 28 49" src="https://github.com/user-attachments/assets/1171b597-4b79-46fd-bd9e-50caab466d45">

if this is OFF -> then Wipe&Slice will NOT introduce BeatSync to any slices.
if this is ON -> then Wipe&Slice will introduce BeatSync to any slices.

**Comment by tkna91** [comment]
Yes, I was thinking perhaps I could handle such a pattern, but it seems that `Wipe & Slice` will not work as expected because of discrepancies in the `Beatsync Enable/Disable` settings for the source and sliced samples.

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/issues/565

> **Apply the following to the first slice source:**
> 
> 4. Beatsync: Enable
> 
> **Apply the following to all sliced samples (other than the first slice source):**
> 
> 9. Beatsync: Disable

It would be better to design this as a dedicated feature, as per #565, instead of `Wipe & Slices Settings`.

**Comment by tkna91** [comment]
However, it would be nice to have the option to set up the above.
Slicing a drumf phrase into a drum set is standard usage.

**Comment by esaruoho** [comment]
@tkna91 please be more specific. are you talking you want "Drum Phrases" aka Phrases from the Phrase Editor, sliced to slices?

**Comment by tkna91** [comment]
No, it would be better to say “drum loop” instead of drum phrase.
In other words, when slicing a drum loop, the slice source and the sliced sample may have different settings for the required properties, as shown below.
This is why it would be useful to have separate settings for both.

> **Apply the following to the first slice source:**
> 
> 4. Beatsync: Enable
> 5. Mode: Percussion/Texture
> 6. Loop: Forward
> 7. Mute Group: Group1
> 8. Playback: Autoseek
> 
> **Apply the following to all sliced samples (other than the first slice source):**
> 
> 1. Beatsync: Disable
> 2. Trigger: One-Shot
> 3. Playback: Autofade

https://github.com/user-attachments/assets/2bfa6fa8-6bba-4416-b6e4-50c53a2f23a0
