### ISSUE TITLE
Render the currently selected sample to the currently selected file in the Disk Browser

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#612]
After correcting a sample with a misaligned loop seam, it would be useful to be able to render it immediately to the file under selection in the Disk Browser.

Ideally, the destination file format should be the same as the file currently selected in the Disk Browser. That way, the output will be the same whether the original sample is a wav, mp3, or flac. If it is difficult to implement this, you can fix the file format as flac or wav.

https://github.com/user-attachments/assets/d8a88874-bfd3-42c4-9027-bb12e96f7c81

**Comment by tkna91** [comment]
Perhaps ffmpeg could handle this automatically by extension or mimetype.

**Comment by esaruoho** [comment]
blocked by api. api does not have hooks for "which file is selected in disk browser". or "which folder are you in". or "is disk browser focused". or "which tab in disk browser are you in". etc.
please make api feature requests for these

**Comment by esaruoho** [comment]
closing until they address it :+1: fingers crossed
