### ISSUE TITLE
[Groovebox] Adding Yxx

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#623]
- If you specify a value of `Yxx`, the FX column of the corresponding note will be filled with the value `Yxx`
- Clicking `Randomize` will write a random value between `Y00`-`YFF` to the above

![image](https://github.com/user-attachments/assets/68e9a897-1f05-4798-a1a9-1554e785c4f4)

**Comment by tkna91** [comment]
This is how I currently envision it.

- If you don't set anything, the `Yxx` value will be represented as `--` and so on, and the probability will not be valid.
- If you set a value, that `Yxx` value will be written in the global FX of each checkbox note.
- If you click `Randomaize`, one of the values `Y00`-`YFF` will be written in the global FX of the note of each checkbox. This is a random but single value. For example, if the value is `Y88`, then the value `Y88` will be written to all the global FX of the note of each checkbox.

**Comment by esaruoho** [comment]
ok sounds like i've done all of this except the Randomize Yxx. good idea.

**Comment by esaruoho** [comment]
![yxx probability slider, randomize, randomize all](https://github.com/user-attachments/assets/f0115730-b573-4c7c-9a99-b347b742a090)
