### ISSUE TITLE
[DynamicView] Settings are reset on Paketti update

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#627]
The presence of the `preferencesDynamicView.xml` file as a default setting causes user settings to be overwritten when Paketti is updated.
It seems better to have no default settings file.

**Comment by esaruoho** [comment]
they need to be stored somewhere. otherwise they will not be stored at all. i'll look into this. thanks for noticing.

**Comment by tkna91** [comment]
Even if the file does not exist, it appears to be generated by the configuration.
If the default file does not exist, updating Paketti would not overwrite the user's configuration file with that file.

https://github.com/user-attachments/assets/0fe2dc4b-46f5-4104-9d08-f25f45d13ded

**Comment by tkna91** [comment]
I just confirmed the update with the following release version. The settings are not overwritten.
It looks like there was no problem because the `preferencesDynamicView.xml` was not included in the xrnx
https://github.com/esaruoho/org.lackluster.Paketti.xrnx/releases/tag/20241016200749

**Comment by tkna91** [comment]
merge this and other xml into `preferences.xml

**Comment by esaruoho** [comment]
i've fixed it in github releases, but it is not fixed in private Direct Message releases. i have been trying to solve it but to no avail as of yet.

there is a different ticket about combining preferences already.
https://github.com/esaruoho/org.lackluster.Paketti.xrnx/issues/405

closing for now
