### ISSUE TITLE
[Groovebox] Sequential multiple selection of checkboxes by mouse dragging

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#636]
In Groovebox's operation system, it is often the case that a series of buttons are stroked with a finger to enable or disable them all together.
It would be useful if such operation could be performed by some expression.

https://github.com/user-attachments/assets/d78b04fc-e994-4a0e-8eff-68035486ef52

**Comment by esaruoho** [comment]
please request new UI elements in the API Feature request area. this can't be done otherwise. closing and adding label "blockedByAPI"

**Comment by tkna91** [comment]
I requested https://forum.renoise.com/t/the-api-wishlist-thread/29285/390
