### ISSUE TITLE
Individual Instrument Drumkit

### ISSUE THREAD

**Issue by ghost** [esaruoho/org.lackluster.Paketti.xrnx#77]
As a continuation from the forum 

https://forum.renoise.com/t/post-your-favorite-tools/72255/16

Would it be possible to load up drumkits as individual instruments rather than sample slots in one sample instrument?

For example: Instrument slots 000-010 have are each loaded with a single sample(or multiple), that particular bank of instruments is saved somehow in the tool maybe as xml or something. This particular bank of instruments can then be saved and recalled in any other project. 

So this actually works more like a bank of instruments than a kit.

**Comment by esaruoho** [comment]
@icasiino ok so what i'm getting from this is that you might want say 10 specific instruments to be loaded to a specific instrument box amount of slots, and that that would be preferred to be automated.

well, i don't see any reason why not. it is trivial to add new instruments at specific instrument indexes, for instance, 00-10.

if you could give me a XRNS example of something like this, i could dissect it, make it into a shortcut and make sure it loads.

do you also want them to be in specific instrument slots? i.e. thinking like kick 00 snare 01  or something like that?

the preparation of it would be trivial to do, and an interesting challenge. so tell me more.

**Comment by icasiino** [comment]
That's exactly what I had in mind, but with a way for the user to create their own set of instruments that could be loaded and reloaded. Anyway Paketti could use an external file format to save the users personal "instrument bank" rather than a predetermined instruments set by Paketti?

**Comment by esaruoho** [comment]
i'm tagging this as `maybe` and closing as not planned for now. it's not a bad idea. but it requires a xml format and all kinds of tweaking for it to work.
