### ISSUE TITLE
View slices in original sample with padding - for adjusting slices better

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#85]
suggestion was posted to 
https://forum.renoise.com/t/mappable-shortcuts-to-navigate-through-slice-markers/68119

- i have a working prototype for this but it has some bugs, and need a previous slice goer, and a way of getting rid of the buggy "didn't exactly show" system in one slice, and also resetting the sliceCounter
![Slice showing with padding](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/c0babf2e-bd67-4637-8659-dd7944662483)

anyway, it's going pretty good.

for the attention of @tkna91

**Comment by esaruoho** [comment]
now added "reset to slice1". and working on "jump to previous slice"

**Comment by tkna91** [comment]
The following two appear to be what was requested in the forum

- Select previous slice marker
- Select next slice marker

I feel that the following would make the user's work more efficient

- Move selected slice marker to the left
- Move selected slice marker to the right

I feel like the unit of movement should be the same as the cursor movement unit (1 pixel?)

**Comment by esaruoho** [comment]
> - Move selected slice marker to the left
> 
> - Move selected slice marker to the right
> 
> 
> 
> I feel like the unit of movement should be the same as the cursor movement unit (1 pixel?)

That (the idea) is already in https://github.com/esaruoho/org.lackluster.Paketti.xrnx/issues/86

**Comment by esaruoho** [comment]
i think i'll close this. it works pretty alright.
